#!/usr/bin/env bash
# Apache Guacamole local stack — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing Apache Guacamole (Docker-based)…"
require docker

GUAC_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/sindri/guacamole"
mkdir -p "$GUAC_DIR"

# Write user-mapping if absent (single local account)
if [[ ! -f "$GUAC_DIR/user-mapping.xml" ]]; then
    cat > "$GUAC_DIR/user-mapping.xml" <<'EOF'
<user-mapping>
    <authorize username="admin" password="admin" encoding="plain">
        <connection name="local-desktop">
            <protocol>vnc</protocol>
            <param name="hostname">localhost</param>
            <param name="port">5901</param>
        </connection>
    </authorize>
</user-mapping>
EOF
    info "Created default user-mapping.xml (change the password before use)."
fi

# Launch guacamole + guacd
if docker ps --format '{{.Names}}' 2>/dev/null | grep -q sindri-guacd; then
    warn "Guacamole is already running. Skipping."
else
    info "Starting guacd (daemon)…"
    docker run -d --name sindri-guacd --restart unless-stopped \
        guacamole/guacd \
        || die "Failed to start guacd."

    info "Starting Guacamole web app…"
    docker run -d --name sindri-guacamole --restart unless-stopped \
        --link sindri-guacd:guacd \
        -v "$GUAC_DIR/user-mapping.xml:/etc/guacamole/user-mapping.xml:ro" \
        -e GUACD_HOSTNAME=guacd \
        -p 8080:8080 \
        guacamole/guacamole \
        || die "Failed to start Guacamole."
fi

info "Guacamole: http://localhost:8080/guacamole  (admin/admin)"
warn "Change the default password immediately after first login."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
