#!/usr/bin/env python3
"""
generate_scripts.py

Generates lifecycle management shell scripts for all script-backend components:
  install.sh   — install the component
  upgrade.sh   — upgrade to the latest published version
  uninstall.sh — remove the component and its data
  validate.sh  — verify the component is correctly installed

Run:
    python3 tools/generate_scripts.py [--dry-run]
"""
from __future__ import annotations
import argparse, pathlib, stat

COMP_DIR = pathlib.Path(__file__).parent.parent / "registry-core" / "components"

# ── shared header ─────────────────────────────────────────────────────────────
def header(title: str, script: str, version: str = "") -> str:
    want = f'WANT="${{SINDRI_COMPONENT_VERSION:-{version}}}"' if version else 'WANT="${SINDRI_COMPONENT_VERSION:-}"'
    return f"""\
#!/usr/bin/env bash
# {title} — {script}
# Generated by tools/generate_scripts.py
set -euo pipefail

# ── helpers ───────────────────────────────────────────────────────────────────
_g="\\033[0;32m" _y="\\033[0;33m" _r="\\033[0;31m" _b="\\033[0m"
info()    {{ echo -e "${{_g}}[sindri]${{_b}} $*"; }}
warn()    {{ echo -e "${{_y}}[warn]${{_b}}  $*"; }}
die()     {{ echo -e "${{_r}}[error]${{_b}} $*" >&2; exit 1; }}
has()     {{ command -v "$1" &>/dev/null; }}
require() {{ has "$1" || die "Required: $1 — install it before running this script."; }}

# ── version contract (ADR-024) ─────────────────────────────────────────────────
# SINDRI_COMPONENT_VERSION: injected by the sindri CLI before invoking this script.
# Carries the exact version declared in registry component.yaml.
# Scripts MUST exit 0 without side effects when already at target version.
{want}

# Extract semver from binary's version output
version_of() {{
    "${{1}}" --version 2>/dev/null | grep -oE '[0-9]+\\.[0-9]+(\\.[0-9]+)?' | head -1 \\
    || "${{1}}" version  2>/dev/null | grep -oE '[0-9]+\\.[0-9]+(\\.[0-9]+)?' | head -1 \\
    || echo ""
}}

# Return 0 (true) and print status if $1 binary is already at $WANT.
# Return 1 (false) and print upgrade/install intent otherwise.
at_version() {{
    local bin="$1" have
    have=$(version_of "$bin")
    if [[ -n "$WANT" && ( "$have" == "$WANT"* || "$have" == *"$WANT"* ) ]]; then
        info "$bin $WANT already installed. Nothing to do."
        return 0
    fi
    [[ -n "$have" ]] && info "$bin: $have → $WANT" || info "Installing $bin $WANT…"
    return 1
}}

"""

# ── per-component script bodies ───────────────────────────────────────────────
# Each dict maps component name → shell body (appended after the shared header).
INSTALLS: dict[str, str] = {

# ─── SDKMAN (bootstrapper) ────────────────────────────────────────────────────
"sdkman": """\
info "Installing SDKMAN (Software Development Kit Manager)…"

export SDKMAN_DIR="${SDKMAN_DIR:-$HOME/.sdkman}"

if [[ -d "$SDKMAN_DIR" && -f "$SDKMAN_DIR/bin/sdkman-init.sh" ]]; then
    warn "SDKMAN already installed at $SDKMAN_DIR — updating to latest…"
    source "$SDKMAN_DIR/bin/sdkman-init.sh" 2>/dev/null || true
    sdk selfupdate force 2>/dev/null || true
    info "SDKMAN updated."
else
    info "Downloading SDKMAN from https://get.sdkman.io …"
    require curl
    curl -s "https://get.sdkman.io" | bash || die "SDKMAN install failed."
    info "SDKMAN installed."
fi

# Verify
source "$SDKMAN_DIR/bin/sdkman-init.sh" 2>/dev/null || true
has sdk && info "sdk: $(sdk version 2>/dev/null | head -1)" \\
         || info "sdk function will be available in new interactive shells."

info "Run 'source ~/.bashrc' or open a new shell, then: sdk install java"
""",

# ─── DOCKER ───────────────────────────────────────────────────────────────────
"docker": """\
at_version docker && exit 0
info "Configuring Docker…"

# Add current user to docker group for rootless access
if ! groups "${USER:-developer}" 2>/dev/null | grep -q docker; then
    info "Adding ${USER:-developer} to docker group…"
    sudo usermod -aG docker "${USER:-developer}" \\
        && warn "Group change takes effect on next login."
fi

# Write sensible daemon defaults if not already configured
DAEMON_JSON="/etc/docker/daemon.json"
if [[ ! -f "$DAEMON_JSON" ]]; then
    sudo mkdir -p /etc/docker
    sudo tee "$DAEMON_JSON" > /dev/null <<'EOF'
{
    "storage-driver": "overlay2",
    "data-root": "/var/lib/docker",
    "log-level": "warn",
    "live-restore": true
}
EOF
    info "Created $DAEMON_JSON with overlay2 storage driver."
fi

# Start daemon if not running (non-systemd container environments)
if ! docker info &>/dev/null; then
    info "Starting Docker daemon…"
    sudo nohup dockerd > "${HOME}/.local/state/dockerd.log" 2>&1 &
    for i in {1..15}; do
        docker info &>/dev/null && break || sleep 1
    done
fi

docker info &>/dev/null && info "Docker daemon reachable." \\
                        || warn "Docker daemon may still be starting. Try: sudo docker info"
""",

# ─── DOTNET ───────────────────────────────────────────────────────────────────
"dotnet": """\
info "Installing .NET SDK via Microsoft install script…"
require curl

CHANNEL="${DOTNET_CHANNEL:-LTS}"
INSTALL_DIR="${DOTNET_INSTALL_DIR:-$HOME/.dotnet}"
export DOTNET_ROOT="$INSTALL_DIR"
export PATH="$INSTALL_DIR:$PATH"

at_version dotnet && exit 0

info "Fetching dotnet-install.sh (channel: $CHANNEL)…"
curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin \\
    --channel "$CHANNEL" \\
    --install-dir "$INSTALL_DIR" \\
    --no-path \\
    || die ".NET install failed."

# Persist to shell rc
for rc in ~/.bashrc ~/.zshrc; do
    [[ -f "$rc" ]] && grep -q "DOTNET_ROOT" "$rc" && continue
    [[ -f "$rc" ]] && cat >> "$rc" <<'RCEOF'

# .NET SDK
export DOTNET_ROOT="$HOME/.dotnet"
export PATH="$DOTNET_ROOT:$DOTNET_ROOT/tools:$PATH"
RCEOF
done

info ".NET $(dotnet --version 2>/dev/null || echo 'installed') ready."
""",

# ─── GCLOUD ───────────────────────────────────────────────────────────────────
"gcloud": """\
info "Installing Google Cloud SDK…"
require curl

at_version gcloud && exit 0

# Use the official interactive-less installer
info "Downloading Google Cloud SDK installer…"
export CLOUDSDK_CORE_DISABLE_PROMPTS=1
curl -sSL https://sdk.cloud.google.com | bash -s -- --disable-prompts \\
    || die "Google Cloud SDK install failed."

# Source the rc update
SDK_DIR="${CLOUDSDK_ROOT_DIR:-$HOME/google-cloud-sdk}"
[[ -f "$SDK_DIR/path.bash.inc" ]] && source "$SDK_DIR/path.bash.inc"
[[ -f "$SDK_DIR/completion.bash.inc" ]] && source "$SDK_DIR/completion.bash.inc"

has gcloud && info "gcloud: $(gcloud --version 2>/dev/null | head -1)" \\
           || warn "gcloud installed; start a new shell to activate."
info "Authenticate with: gcloud auth login"
""",

# ─── PHP ──────────────────────────────────────────────────────────────────────
"php": """\
info "Installing PHP and Composer…"

install_via_apt() {
    require apt-get
    sudo apt-get update -qq
    sudo apt-get install -y -qq \\
        php php-cli php-common php-curl php-json php-mbstring \\
        php-xml php-zip php-intl php-gd 2>/dev/null
}

install_via_dnf() {
    require dnf
    sudo dnf install -y php php-cli php-common php-curl php-json \\
        php-mbstring php-xml php-zip php-intl 2>/dev/null
}

install_via_brew() {
    require brew
    brew install php
}

if has php; then
    warn "PHP already installed: $(php --version | head -1). Skipping."
else
    case "$(uname -s)" in
        Linux)
            if has apt-get;  then install_via_apt
            elif has dnf;    then install_via_dnf
            else die "Unsupported Linux package manager. Install PHP manually."
            fi ;;
        Darwin) install_via_brew ;;
        *) die "Unsupported OS." ;;
    esac
    info "PHP $(php --version 2>/dev/null | head -1 | grep -oE '[0-9]+\\.[0-9]+\\.[0-9]+') installed."
fi

# Install Composer
if has composer; then
    warn "Composer already installed: $(composer --version 2>/dev/null | head -1). Skipping."
else
    info "Installing Composer…"
    require curl
    EXPECTED_CHECKSUM="$(curl -sS https://composer.github.io/installer.sig)"
    php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');"
    ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', '/tmp/composer-setup.php');")"
    [[ "$EXPECTED_CHECKSUM" == "$ACTUAL_CHECKSUM" ]] || die "Composer installer checksum mismatch."
    php /tmp/composer-setup.php --quiet --install-dir="$HOME/.local/bin" --filename=composer
    rm /tmp/composer-setup.php
    info "Composer $(composer --version 2>/dev/null | head -1) installed."
fi
""",

# ─── PLAYWRIGHT ───────────────────────────────────────────────────────────────
"playwright": """\
info "Installing Playwright and browsers…"
require node
require npm

# Playwright version is checked via npx since it may be project-local
_pw_ver=$(npx playwright --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 || echo "")
if [[ -n "$WANT" && "$_pw_ver" == "$WANT"* ]]; then
    info "playwright $WANT already installed. Nothing to do."
    exit 0
fi
[[ -n "$_pw_ver" ]] && info "playwright: $_pw_ver → $WANT" || info "Installing playwright $WANT…"

info "Installing Playwright globally…"
npm install -g playwright \\
    || die "npm install -g playwright failed."

info "Installing browser binaries…"
if [[ "${CI:-}" == "true" || "${GITHUB_ACTIONS:-}" == "true" ]]; then
    warn "CI mode: skipping browser downloads."
    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 playwright install 2>/dev/null || true
else
    playwright install || die "playwright install failed."
    playwright install-deps 2>/dev/null || warn "Some system deps may be missing (run with sudo for full install-deps)."
fi

info "Playwright $(playwright --version 2>/dev/null) ready."
""",

# ─── OLLAMA ───────────────────────────────────────────────────────────────────
"ollama": """\
info "Installing Ollama LLM runtime…"
require curl

if [[ "${CI:-}" == "true" || "${GITHUB_ACTIONS:-}" == "true" ]]; then
    warn "CI mode: skipping Ollama (large download). Install manually: curl -fsSL https://ollama.com/install.sh | sh"
    exit 0
fi

at_version ollama && exit 0

case "$(uname -s)" in
    Linux)
        ARCH="$(uname -m)"
        [[ "$ARCH" == "x86_64" ]]  && URL="https://ollama.com/download/ollama-linux-amd64.tar.zst"
        [[ "$ARCH" == "aarch64" ]] && URL="https://ollama.com/download/ollama-linux-arm64.tar.zst"
        [[ -z "${URL:-}" ]] && die "Unsupported arch: $ARCH"
        mkdir -p "$HOME/.local/bin"
        require zstd || { sudo apt-get install -y zstd 2>/dev/null || sudo dnf install -y zstd 2>/dev/null; }
        info "Downloading Ollama (~800 MB)…"
        curl -fsSL "$URL" -o /tmp/ollama.tar.zst
        tar -I zstd -xf /tmp/ollama.tar.zst -C /tmp
        mv /tmp/bin/ollama "$HOME/.local/bin/ollama"
        chmod +x "$HOME/.local/bin/ollama"
        rm -rf /tmp/ollama.tar.zst /tmp/bin
        ;;
    Darwin)
        if has brew; then brew install ollama
        else die "Install Ollama for macOS from https://ollama.com/download"; fi
        ;;
    *) die "Unsupported OS." ;;
esac

has ollama && info "Ollama $(ollama --version 2>/dev/null | head -1) installed." \\
          || die "Ollama binary not found after install."
info "Start Ollama with: ollama serve"
info "Pull a model:      ollama pull llama3.2"
""",

# ─── GOOSE (Block's AI agent) ─────────────────────────────────────────────────
"goose": """\
info "Installing Goose AI agent (Block)…"
require curl

at_version goose && exit 0

info "Fetching official Goose installer…"
CONFIGURE=false curl -fsSL \\
    https://github.com/block/goose/releases/download/stable/download_cli.sh | bash \\
    || die "Goose install failed."

hash -r 2>/dev/null || true
has goose || die "Goose binary not found after install."
info "Goose $(goose --version 2>/dev/null) installed."
info "Configure your LLM provider: goose configure"
info "Start a session:              goose session"
""",

# ─── PULUMI ───────────────────────────────────────────────────────────────────
"pulumi": """\
info "Installing Pulumi IaC CLI…"
require curl

at_version pulumi && exit 0

info "Downloading Pulumi installer…"
curl -fsSL https://get.pulumi.com | sh || die "Pulumi install failed."

# Ensure PATH includes ~/.pulumi/bin
export PATH="$HOME/.pulumi/bin:$PATH"
has pulumi && info "Pulumi $(pulumi version 2>/dev/null) installed." \\
          || die "Pulumi not found after install."
info "Create a project: pulumi new"
""",

# ─── CROSSPLANE CLI ───────────────────────────────────────────────────────────
"crossplane": """\
info "Installing Crossplane CLI (up)…"
require curl

at_version up && exit 0

info "Fetching Upbound CLI (crossplane)…"
curl -sL "https://cli.upbound.io" | sh || die "Crossplane CLI install failed."

has up && info "Crossplane CLI (up) $(up --version 2>/dev/null) ready." \\
       || die "up binary not found after install."
info "Log in: up login"
info "Docs:   https://docs.upbound.io/cli"
""",

# ─── SUPABASE CLI ─────────────────────────────────────────────────────────────
"supabase-cli": """\
info "Installing Supabase CLI…"

at_version supabase && exit 0

case "$(uname -s)" in
    Darwin)
        require brew
        brew install supabase/tap/supabase ;;
    Linux)
        require curl
        # Download latest binary from GitHub releases
        ARCH="$(uname -m)"
        [[ "$ARCH" == "x86_64" ]]  && ARCH="linux_amd64"
        [[ "$ARCH" == "aarch64" ]] && ARCH="linux_arm64"
        LATEST=$(curl -sSf https://api.github.com/repos/supabase/cli/releases/latest \\
                    | grep '"tag_name"' | head -1 | grep -oE 'v[0-9.]+')
        [[ -z "$LATEST" ]] && die "Could not determine latest Supabase CLI version."
        URL="https://github.com/supabase/cli/releases/download/${LATEST}/supabase_${ARCH}.tar.gz"
        mkdir -p "$HOME/.local/bin"
        curl -fsSL "$URL" | tar -xz -C "$HOME/.local/bin" supabase
        chmod +x "$HOME/.local/bin/supabase" ;;
    *)
        die "Unsupported OS." ;;
esac

has supabase && info "Supabase CLI $(supabase --version 2>/dev/null) ready." \\
            || die "Supabase CLI not found after install."
info "Start local dev: supabase start"
""",

# ─── MONITORING (Prometheus + Grafana local stack) ────────────────────────────
"monitoring": """\
info "Installing local monitoring stack (Prometheus + Grafana via Docker)…"
require docker

MONITORING_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/sindri/monitoring"
mkdir -p "$MONITORING_DIR"/{prometheus,grafana}

# Write a minimal Prometheus config if absent
if [[ ! -f "$MONITORING_DIR/prometheus/prometheus.yml" ]]; then
    cat > "$MONITORING_DIR/prometheus/prometheus.yml" <<'EOF'
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
EOF
    info "Created minimal prometheus.yml."
fi

# Simple docker-compose-style launch function (no compose dependency)
if docker ps --format '{{.Names}}' 2>/dev/null | grep -q "sindri-prometheus"; then
    warn "sindri-prometheus container already running. Skipping."
else
    info "Starting Prometheus container…"
    docker run -d --name sindri-prometheus --restart unless-stopped \\
        -p 9090:9090 \\
        -v "$MONITORING_DIR/prometheus:/etc/prometheus:ro" \\
        prom/prometheus:latest \\
        || warn "Failed to start Prometheus — Docker may not be running."
fi

if docker ps --format '{{.Names}}' 2>/dev/null | grep -q "sindri-grafana"; then
    warn "sindri-grafana container already running. Skipping."
else
    info "Starting Grafana container…"
    docker run -d --name sindri-grafana --restart unless-stopped \\
        -p 3001:3000 \\
        -v "$MONITORING_DIR/grafana:/var/lib/grafana" \\
        grafana/grafana:latest \\
        || warn "Failed to start Grafana — Docker may not be running."
fi

info "Prometheus: http://localhost:9090"
info "Grafana:    http://localhost:3001  (admin/admin)"
""",

# ─── GUACAMOLE ────────────────────────────────────────────────────────────────
"guacamole": """\
info "Installing Apache Guacamole (Docker-based)…"
require docker

GUAC_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/sindri/guacamole"
mkdir -p "$GUAC_DIR"

# Write user-mapping if absent (single local account)
if [[ ! -f "$GUAC_DIR/user-mapping.xml" ]]; then
    cat > "$GUAC_DIR/user-mapping.xml" <<'EOF'
<user-mapping>
    <authorize username="admin" password="admin" encoding="plain">
        <connection name="local-desktop">
            <protocol>vnc</protocol>
            <param name="hostname">localhost</param>
            <param name="port">5901</param>
        </connection>
    </authorize>
</user-mapping>
EOF
    info "Created default user-mapping.xml (change the password before use)."
fi

# Launch guacamole + guacd
if docker ps --format '{{.Names}}' 2>/dev/null | grep -q sindri-guacd; then
    warn "Guacamole is already running. Skipping."
else
    info "Starting guacd (daemon)…"
    docker run -d --name sindri-guacd --restart unless-stopped \\
        guacamole/guacd \\
        || die "Failed to start guacd."

    info "Starting Guacamole web app…"
    docker run -d --name sindri-guacamole --restart unless-stopped \\
        --link sindri-guacd:guacd \\
        -v "$GUAC_DIR/user-mapping.xml:/etc/guacamole/user-mapping.xml:ro" \\
        -e GUACD_HOSTNAME=guacd \\
        -p 8080:8080 \\
        guacamole/guacamole \\
        || die "Failed to start Guacamole."
fi

info "Guacamole: http://localhost:8080/guacamole  (admin/admin)"
warn "Change the default password immediately after first login."
""",

# ─── GITHUB-CLI (wrapper — binary:gh handles the download) ───────────────────
"github-cli": """\
info "Configuring GitHub CLI…"
require gh

if gh auth status &>/dev/null; then
    warn "GitHub CLI already authenticated."
else
    info "Authenticating with GitHub (browser flow)…"
    gh auth login --web --git-protocol https \\
        || warn "Authentication skipped. Run 'gh auth login' to authenticate."
fi

info "gh $(gh --version 2>/dev/null | head -1) ready."
info "Common commands: gh repo clone, gh pr create, gh issue list"
""",

# ─── TMUX-WORKSPACE ───────────────────────────────────────────────────────────
"tmux-workspace": """\
info "Installing tmux workspace layouts and helpers…"

# Ensure tmux is present
if ! has tmux; then
    case "$(uname -s)" in
        Darwin) has brew && brew install tmux || die "Install tmux: brew install tmux" ;;
        Linux)  has apt-get && sudo apt-get install -y tmux \\
                || has dnf && sudo dnf install -y tmux \\
                || die "Install tmux via your package manager." ;;
    esac
fi

TMUX_CONF="$HOME/.tmux.conf"
if [[ ! -f "$TMUX_CONF" ]]; then
    cat > "$TMUX_CONF" <<'EOF'
# sindri tmux defaults
set -g default-terminal "screen-256color"
set -g history-limit 50000
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display "Config reloaded."
EOF
    info "Created ~/.tmux.conf with sensible defaults."
else
    warn "~/.tmux.conf already exists — not overwriting."
fi

# Install tmux Plugin Manager (optional, idempotent)
TPM_DIR="$HOME/.tmux/plugins/tpm"
if [[ ! -d "$TPM_DIR" ]]; then
    require git
    git clone --depth 1 https://github.com/tmux-plugins/tpm "$TPM_DIR" 2>/dev/null \\
        && info "tmux Plugin Manager installed. Start tmux and press prefix+I to install plugins."
fi

has tmux && info "tmux $(tmux -V) ready." || die "tmux not found."
""",

# ─── XFCE-UBUNTU ──────────────────────────────────────────────────────────────
"xfce-ubuntu": """\
info "Installing XFCE desktop environment (Ubuntu/Debian)…"
require apt-get

if dpkg -l xfce4 &>/dev/null 2>&1; then
    warn "XFCE already installed."
else
    info "Installing XFCE4 and essentials…"
    sudo apt-get update -qq
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \\
        xfce4 xfce4-goodies xrdp dbus-x11 x11vnc \\
        || die "XFCE install failed."
fi

# Configure xRDP to use XFCE
if has xrdp; then
    echo "startxfce4" | sudo tee /etc/skel/.xsession > /dev/null
    echo "startxfce4" > "$HOME/.xsession"
    sudo systemctl enable xrdp 2>/dev/null || true
    sudo systemctl start  xrdp 2>/dev/null || true
    info "xRDP configured. Connect via Remote Desktop on port 3389."
fi

info "XFCE desktop ready."
""",

# ─── MCP SERVERS ─────────────────────────────────────────────────────────────
"context7-mcp": """\
info "Registering Context7 MCP server with Claude Code…"
require npx
require claude

if claude mcp list 2>/dev/null | grep -q "context7"; then
    warn "Context7 MCP server already registered. Skipping."
    exit 0
fi

info "Adding Context7 MCP server…"
claude mcp add context7 --scope user -- npx -y @upstash/context7-mcp \\
    || die "Failed to register Context7 MCP server."

info "Context7 MCP server registered."
info "Verify with: claude mcp list"
""",

"jira-mcp": """\
info "Registering Jira MCP server with Claude Code…"
require npx
require claude

if claude mcp list 2>/dev/null | grep -q "jira"; then
    warn "Jira MCP server already registered. Skipping."
    exit 0
fi

info "Adding Jira MCP server…"
claude mcp add jira --scope user -- npx -y @smithery/cli@latest run @sooperset/mcp-atlassian \\
    || die "Failed to register Jira MCP server."

warn "Configure Jira credentials: ATLASSIAN_URL, ATLASSIAN_USER_EMAIL, ATLASSIAN_API_TOKEN"
info "Jira MCP server registered."
info "Verify with: claude mcp list"
""",

"linear-mcp": """\
info "Registering Linear MCP server with Claude Code…"
require npx
require claude

if claude mcp list 2>/dev/null | grep -q "linear"; then
    warn "Linear MCP server already registered. Skipping."
    exit 0
fi

info "Adding Linear MCP server…"
claude mcp add linear --scope user -- npx -y @linear/mcp-server \\
    || die "Failed to register Linear MCP server."

warn "Set LINEAR_API_KEY environment variable to authenticate."
info "Linear MCP server registered. Verify with: claude mcp list"
""",

"excalidraw-mcp": """\
info "Registering Excalidraw MCP server with Claude Code…"
require npx
require claude

if claude mcp list 2>/dev/null | grep -q "excalidraw"; then
    warn "Excalidraw MCP server already registered. Skipping."
    exit 0
fi

info "Adding Excalidraw MCP server…"
claude mcp add excalidraw --scope user -- npx -y excalidraw-mcp \\
    || die "Failed to register Excalidraw MCP server."

info "Excalidraw MCP server registered. Verify with: claude mcp list"
""",

"notebooklm-mcp-cli": """\
info "Registering NotebookLM MCP bridge with Claude Code…"
require python3
require claude

# Install the MCP bridge via pip/uv
if has uv; then
    uv tool install notebooklm-mcp 2>/dev/null \\
        || warn "notebooklm-mcp not on PyPI; may need manual install."
elif has pip3; then
    pip3 install --user notebooklm-mcp 2>/dev/null \\
        || warn "notebooklm-mcp not on PyPI; may need manual install."
fi

if claude mcp list 2>/dev/null | grep -q "notebooklm"; then
    warn "NotebookLM MCP bridge already registered. Skipping."
    exit 0
fi

info "Adding NotebookLM MCP bridge…"
claude mcp add notebooklm --scope user -- python3 -m notebooklm_mcp \\
    || die "Failed to register NotebookLM MCP bridge."

info "NotebookLM MCP bridge registered. Verify with: claude mcp list"
""",

"pal-mcp-server": """\
info "Registering PAL MCP server with Claude Code…"
require claude

if claude mcp list 2>/dev/null | grep -q "pal"; then
    warn "PAL MCP server already registered. Skipping."
    exit 0
fi

info "Adding PAL MCP server…"
claude mcp add pal --scope user -- npx -y @beehiveinnovations/pal-mcp-server \\
    || die "Failed to register PAL MCP server."

info "PAL MCP server registered. Verify with: claude mcp list"
""",

# ─── CLAUDE / SINDRI ECOSYSTEM ────────────────────────────────────────────────
"claude-code-mux": """\
info "Setting up Claude Code session multiplexer…"
require tmux
require claude

MUX_BIN="$HOME/.local/bin/claude-mux"
mkdir -p "$HOME/.local/bin"

cat > "$MUX_BIN" <<'MUXEOF'
#!/usr/bin/env bash
# claude-mux — open multiple Claude Code sessions in a tmux layout
set -e
SESSION="${1:-claude}"
tmux new-session -d -s "$SESSION" -x 220 -y 50 2>/dev/null || true
tmux split-window -h -t "$SESSION"
tmux split-window -v -t "$SESSION:0.0"
tmux select-pane -t "$SESSION:0.0" && tmux send-keys "claude" Enter
tmux select-pane -t "$SESSION:0.1" && tmux send-keys "claude" Enter
tmux select-pane -t "$SESSION:0.2"
tmux attach-session -t "$SESSION"
MUXEOF
chmod +x "$MUX_BIN"

info "claude-mux installed at $MUX_BIN"
info "Usage: claude-mux [session-name]"
""",

"claude-codepro": """\
info "Installing Claude CodePro workflow bundle…"
require npm
require claude

# Install any npm dev tools used by CodePro workflows
for pkg in tsx vitest prettier eslint; do
    if ! npm list -g "$pkg" &>/dev/null; then
        npm install -g "$pkg" 2>/dev/null || warn "Optional: could not install $pkg"
    fi
done

info "Claude CodePro workflow bundle ready."
info "Requires: Claude Code with CLAUDE.md project configuration."
""",

"claude-marketplace": """\
info "Installing Claude Marketplace skill resolver…"
require npm
require claude

info "Installing @sindri/marketplace-cli…"
npm install -g @sindri/marketplace-cli 2>/dev/null \\
    || npm install -g claudeup 2>/dev/null \\
    || warn "Marketplace CLI package not found on npm. Manual install may be required."

info "Claude Marketplace skill resolver installed."
info "Browse skills: https://claude.ai/marketplace"
""",

"ralph": """\
info "Installing Ralph — personal coding agent…"
require claude
require node

# Ensure Claude Code is configured
if ! claude --version &>/dev/null; then
    die "Claude Code is required. Install with: npm install -g @anthropic-ai/claude-code"
fi

# Ralph is a configuration layer on top of Claude Code
RALPH_DIR="$HOME/.config/sindri/ralph"
mkdir -p "$RALPH_DIR"

cat > "$RALPH_DIR/config.yaml" <<'EOF'
# Ralph configuration
agent: ralph
model: claude-opus-4-7
tools:
  - bash
  - read
  - write
  - edit
memory: persistent
auto_compact: true
EOF

info "Ralph configured at $RALPH_DIR/config.yaml"
info "Start a Ralph session: claude --config $RALPH_DIR/config.yaml"
""",

# ─── SPEC / CLARITY TOOLS ────────────────────────────────────────────────────
"spec-kit": """\
info "Installing GitHub Spec Kit (spec-driven development)…"
require python3

# Install via pip/uv
if has uv; then
    uv tool install spec-kit 2>/dev/null || true
elif has pip3; then
    pip3 install --user spec-kit 2>/dev/null || true
fi

# Fallback: clone from GitHub if not available as package
if ! has spec; then
    require git
    SPEC_DIR="$HOME/.local/share/sindri/spec-kit"
    if [[ -d "$SPEC_DIR" ]]; then
        info "Updating spec-kit…"
        git -C "$SPEC_DIR" pull --ff-only 2>/dev/null || true
    else
        git clone --depth 1 https://github.com/sindri-dev/spec-kit "$SPEC_DIR" 2>/dev/null \\
            || warn "Could not clone spec-kit. Install manually."
    fi
    [[ -f "$SPEC_DIR/spec" ]] && { cp "$SPEC_DIR/spec" "$HOME/.local/bin/spec"; chmod +x "$HOME/.local/bin/spec"; }
fi

has spec && info "spec-kit installed: $(spec --version 2>/dev/null || echo ok)" \\
         || warn "spec-kit installed but 'spec' not in PATH. Add ~/.local/bin to PATH."
""",

"clarity": """\
info "Installing Clarity spec generator CLI…"
require python3

if has uv; then
    uv tool install clarity-cli 2>/dev/null || true
elif has pip3; then
    pip3 install --user clarity-cli 2>/dev/null || true
fi

if ! has clarity; then
    require git
    CLARITY_DIR="$HOME/.local/share/sindri/clarity"
    if [[ -d "$CLARITY_DIR" ]]; then
        git -C "$CLARITY_DIR" pull --ff-only 2>/dev/null || true
    else
        git clone --depth 1 https://github.com/sindri-dev/clarity "$CLARITY_DIR" 2>/dev/null \\
            || warn "Could not clone clarity. Install manually."
    fi
fi

info "Clarity spec generator ready."
""",

# ─── REASONING / EXPERIMENTATION TOOLS ───────────────────────────────────────
"rtk": """\
info "Installing Reasoning Toolkit (rtk)…"
require python3

if has uv; then
    uv tool install rtk 2>/dev/null || warn "rtk not on PyPI — trying npm…"
fi

if ! has rtk && has npm; then
    npm install -g @sindri/rtk 2>/dev/null || warn "rtk not on npm."
fi

has rtk && info "rtk installed." || warn "rtk not found on public registries. May need manual install."
""",

"draupnir": """\
info "Installing draupnir infra forge…"
require node

npm install -g @sindri/draupnir 2>/dev/null \\
    || warn "draupnir not found on npm. May need manual install from source."

has draupnir && info "draupnir installed: $(draupnir --version 2>/dev/null || echo ok)" \\
             || warn "draupnir installed but not in PATH."
""",

"openfang": """\
info "Installing openfang offensive-security learning harness…"
require python3

OPENFANG_DIR="$HOME/.local/share/sindri/openfang"
require git

if [[ -d "$OPENFANG_DIR" ]]; then
    info "Updating openfang…"
    git -C "$OPENFANG_DIR" pull --ff-only 2>/dev/null || true
else
    git clone --depth 1 https://github.com/sindri-dev/openfang "$OPENFANG_DIR" 2>/dev/null \\
        || die "Failed to clone openfang."
fi

# Install Python deps if requirements.txt exists
if [[ -f "$OPENFANG_DIR/requirements.txt" ]]; then
    python3 -m pip install --user -r "$OPENFANG_DIR/requirements.txt" 2>/dev/null || true
fi

info "openfang installed at $OPENFANG_DIR"
warn "For security-training purposes only. Use only on systems you own or have permission to test."
""",

"shannon": """\
info "Installing Shannon (signal processing playground)…"
require python3

for pkg in numpy scipy matplotlib jupyter; do
    python3 -m pip install --user "$pkg" 2>/dev/null \\
        || warn "Could not install $pkg — some Shannon features may be unavailable."
done

SHANNON_DIR="$HOME/.local/share/sindri/shannon"
require git
if [[ -d "$SHANNON_DIR" ]]; then
    git -C "$SHANNON_DIR" pull --ff-only 2>/dev/null || true
else
    git clone --depth 1 https://github.com/sindri-dev/shannon "$SHANNON_DIR" 2>/dev/null \\
        || warn "Could not clone shannon. Install dependencies only."
fi

info "Shannon signal processing playground ready."
""",
}

# ── upgrade bodies ────────────────────────────────────────────────────────────
# ADR-024: upgrade.sh delegates to install.sh for all script components.
# The CLI sets SINDRI_COMPONENT_VERSION to the new target; install.sh is
# version-aware and handles the transition from any previous state.
#
# Exceptions: tools with a native self-update command that is faster than
# re-downloading (sdkman, gcloud). All others use the default.
UPGRADES: dict[str, str] = {
    "sdkman": """\
info "Upgrading SDKMAN…"
export SDKMAN_DIR="${SDKMAN_DIR:-$HOME/.sdkman}"
source "$SDKMAN_DIR/bin/sdkman-init.sh" 2>/dev/null \\
    || die "SDKMAN not installed. Run install.sh first."
sdk selfupdate force
info "SDKMAN ready: $(sdk version 2>/dev/null | head -1)"
""",
    "gcloud": """\
info "Upgrading Google Cloud SDK to $WANT…"
require gcloud
gcloud components update --quiet
info "gcloud ready: $(gcloud --version 2>/dev/null | head -1)"
""",
}

# ── uninstall bodies ──────────────────────────────────────────────────────────
UNINSTALLS: dict[str, str] = {
    "sdkman": """\
info "Uninstalling SDKMAN and all managed SDKs…"
export SDKMAN_DIR="${SDKMAN_DIR:-$HOME/.sdkman}"
[[ -d "$SDKMAN_DIR" ]] || { warn "SDKMAN not found at $SDKMAN_DIR."; exit 0; }
read -rp "This will remove ALL SDKs installed via SDKMAN. Continue? [y/N] " ans
[[ "$ans" =~ ^[Yy]$ ]] || { info "Aborted."; exit 0; }
rm -rf "$SDKMAN_DIR"
# Remove shell snippets
for rc in ~/.bashrc ~/.zshrc ~/.profile; do
    [[ -f "$rc" ]] && sed -i '/sdkman/d' "$rc" 2>/dev/null || true
done
info "SDKMAN removed."
""",
    "docker": """\
info "Stopping Sindri Docker containers…"
docker stop sindri-prometheus sindri-grafana 2>/dev/null || true
docker rm   sindri-prometheus sindri-grafana 2>/dev/null || true
info "Sindri Docker monitoring containers removed."
warn "Docker Engine itself was installed by the system and is NOT removed by this script."
warn "To uninstall Docker Engine: sudo apt-get remove docker-ce docker-ce-cli containerd.io"
""",
    "ollama": """\
info "Uninstalling Ollama…"
case "$(uname -s)" in
    Darwin) has brew && brew uninstall ollama 2>/dev/null || true ;;
    Linux)  rm -f "$HOME/.local/bin/ollama" ;;
esac
info "Removing Ollama models (~/.ollama)…"
read -rp "Remove downloaded models (~/.ollama)? [y/N] " ans
[[ "$ans" =~ ^[Yy]$ ]] && rm -rf "$HOME/.ollama" || info "Models retained."
info "Ollama uninstalled."
""",
    "gcloud": """\
info "Uninstalling Google Cloud SDK…"
SDK_DIR="${CLOUDSDK_ROOT_DIR:-$HOME/google-cloud-sdk}"
[[ -d "$SDK_DIR" ]] || { warn "gcloud SDK not found at $SDK_DIR."; exit 0; }
"$SDK_DIR/bin/gcloud" components remove --quiet 2>/dev/null || true
rm -rf "$SDK_DIR"
for rc in ~/.bashrc ~/.zshrc ~/.bash_profile ~/.profile; do
    [[ -f "$rc" ]] && sed -i '/google-cloud-sdk/d' "$rc" 2>/dev/null || true
done
info "Google Cloud SDK removed."
""",
    "pulumi": """\
info "Uninstalling Pulumi…"
rm -rf "$HOME/.pulumi"
for rc in ~/.bashrc ~/.zshrc ~/.profile; do
    [[ -f "$rc" ]] && sed -i '/.pulumi/d' "$rc" 2>/dev/null || true
done
info "Pulumi removed."
""",
    "dotnet": """\
info "Uninstalling .NET SDK…"
DOTNET_DIR="${DOTNET_ROOT:-$HOME/.dotnet}"
rm -rf "$DOTNET_DIR"
for rc in ~/.bashrc ~/.zshrc; do
    [[ -f "$rc" ]] && sed -i '/DOTNET_ROOT/d' "$rc" 2>/dev/null || true
done
info ".NET SDK removed from $DOTNET_DIR."
""",
    "supabase-cli": """\
info "Uninstalling Supabase CLI…"
case "$(uname -s)" in
    Darwin) has brew && brew uninstall supabase/tap/supabase 2>/dev/null || true ;;
    Linux)  rm -f "$HOME/.local/bin/supabase" ;;
esac
info "Supabase CLI removed."
""",
    "guacamole": """\
info "Uninstalling Guacamole (Docker containers)…"
docker stop sindri-guacamole sindri-guacd 2>/dev/null || true
docker rm   sindri-guacamole sindri-guacd 2>/dev/null || true
read -rp "Remove Guacamole data ($HOME/.local/share/sindri/guacamole)? [y/N] " ans
[[ "$ans" =~ ^[Yy]$ ]] && rm -rf "$HOME/.local/share/sindri/guacamole" || info "Data retained."
info "Guacamole removed."
""",
    "monitoring": """\
info "Uninstalling monitoring stack (Docker containers)…"
docker stop sindri-prometheus sindri-grafana 2>/dev/null || true
docker rm   sindri-prometheus sindri-grafana 2>/dev/null || true
read -rp "Remove monitoring data ($HOME/.local/share/sindri/monitoring)? [y/N] " ans
[[ "$ans" =~ ^[Yy]$ ]] && rm -rf "$HOME/.local/share/sindri/monitoring" || info "Data retained."
info "Monitoring stack removed."
""",
    "goose": """\
info "Uninstalling Goose AI agent…"
rm -f "$HOME/.local/bin/goose"
info "Goose removed."
""",
    "playwright": """\
info "Uninstalling Playwright…"
npm uninstall -g playwright 2>/dev/null || true
info "Removing browser binaries…"
npx playwright uninstall --all 2>/dev/null || true
info "Playwright removed."
""",
    "crossplane": """\
info "Uninstalling Crossplane CLI (up)…"
rm -f /usr/local/bin/up "$HOME/.local/bin/up" 2>/dev/null || true
info "Crossplane CLI (up) removed."
""",
    "tmux-workspace": """\
info "Removing Sindri tmux workspace configuration…"
read -rp "Remove ~/.tmux.conf? [y/N] " ans
[[ "$ans" =~ ^[Yy]$ ]] && rm -f "$HOME/.tmux.conf" && info "~/.tmux.conf removed." || info "Skipped."
read -rp "Remove tmux Plugin Manager (~/.tmux/plugins/tpm)? [y/N] " ans
[[ "$ans" =~ ^[Yy]$ ]] && rm -rf "$HOME/.tmux/plugins/tpm" || info "TPM retained."
info "tmux-workspace uninstalled (tmux itself not removed)."
""",
}

# ── validate bodies ───────────────────────────────────────────────────────────
VALIDATES: dict[str, str] = {
    "sdkman": """\
info "Validating SDKMAN installation…"
export SDKMAN_DIR="${SDKMAN_DIR:-$HOME/.sdkman}"
[[ -f "$SDKMAN_DIR/bin/sdkman-init.sh" ]] || die "sdkman-init.sh not found at $SDKMAN_DIR."
source "$SDKMAN_DIR/bin/sdkman-init.sh" 2>/dev/null || true
sdk version 2>/dev/null | head -1 || die "sdk command failed."
info "SDKMAN OK: $(sdk version 2>/dev/null | head -1)"
""",
    "docker": """\
info "Validating Docker installation…"
require docker
docker info &>/dev/null || die "Docker daemon not reachable. Start with: sudo systemctl start docker"
info "Docker OK: $(docker --version)"
""",
    "dotnet": """\
info "Validating .NET SDK…"
require dotnet
dotnet --version >/dev/null || die "dotnet --version failed."
info ".NET OK: $(dotnet --version)"
""",
    "gcloud": """\
info "Validating Google Cloud SDK…"
require gcloud
gcloud --version 2>/dev/null | head -1 || die "gcloud not responding."
info "gcloud OK: $(gcloud --version 2>/dev/null | head -1)"
""",
    "php": """\
info "Validating PHP and Composer…"
require php
php --version | head -1 || die "php --version failed."
require composer
composer --version | head -1 || die "composer --version failed."
info "PHP OK: $(php --version | head -1)"
info "Composer OK: $(composer --version | head -1)"
""",
    "playwright": """\
info "Validating Playwright…"
require npx
npx playwright --version >/dev/null || die "playwright not found."
info "Playwright OK: $(npx playwright --version 2>/dev/null)"
""",
    "ollama": """\
info "Validating Ollama…"
require ollama
ollama --version >/dev/null || die "ollama binary unresponsive."
info "Ollama OK: $(ollama --version 2>/dev/null)"
""",
    "goose": """\
info "Validating Goose…"
require goose
goose --version >/dev/null || die "goose binary unresponsive."
info "Goose OK: $(goose --version 2>/dev/null)"
""",
    "pulumi": """\
info "Validating Pulumi…"
export PATH="$HOME/.pulumi/bin:$PATH"
require pulumi
pulumi version >/dev/null || die "pulumi version failed."
info "Pulumi OK: $(pulumi version 2>/dev/null)"
""",
    "crossplane": """\
info "Validating Crossplane CLI…"
require up
up --version >/dev/null || die "up binary unresponsive."
info "Crossplane CLI OK: $(up --version 2>/dev/null)"
""",
    "supabase-cli": """\
info "Validating Supabase CLI…"
require supabase
supabase --version >/dev/null || die "supabase --version failed."
info "Supabase CLI OK: $(supabase --version 2>/dev/null)"
""",
    "github-cli": """\
info "Validating GitHub CLI…"
require gh
gh --version | head -1 || die "gh not responding."
gh auth status &>/dev/null || warn "Not authenticated. Run: gh auth login"
info "gh OK: $(gh --version 2>/dev/null | head -1)"
""",
}

# ── default generators (used when a component has no specific entry) ───────────

def default_upgrade(name: str) -> str:
    # ADR-024: install.sh is the upgrade path. SINDRI_COMPONENT_VERSION is already
    # set by the CLI before it calls upgrade.sh (and will be forwarded to install.sh).
    return f"""\
info "Upgrading {name} to $WANT…"
SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
exec bash "$SCRIPT_DIR/install.sh"
"""

def default_uninstall(name: str, binary: str | None = None) -> str:
    bin_name = binary or name
    return f"""\
info "Uninstalling {name}…"
rm -f "$HOME/.local/bin/{bin_name}" 2>/dev/null || true
info "{name} binary removed from ~/.local/bin/{bin_name}."
warn "Configuration files and data were NOT removed."
"""

def default_validate(name: str, binary: str | None = None) -> str:
    bin_name = binary or name
    return f"""\
info "Validating {name}…"
require {bin_name}
{bin_name} --version >/dev/null 2>&1 || die "{bin_name} not responding."
info "{name} OK"
"""

# ── generate ──────────────────────────────────────────────────────────────────

SCRIPTS: dict[str, tuple[dict, callable, str]] = {
    # script_filename: (specific_bodies_dict, default_fallback, label)
    "install.sh":   (INSTALLS,   None,            "install"),
    "upgrade.sh":   (UPGRADES,   default_upgrade, "upgrade"),
    "uninstall.sh": (UNINSTALLS, default_uninstall, "uninstall"),
    "validate.sh":  (VALIDATES,  default_validate, "validate"),
}


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate lifecycle scripts for script-backend components")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be written without writing")
    args = parser.parse_args()

    import yaml as _yaml

    total_written = total_skipped = 0

    for d in sorted(COMP_DIR.iterdir()):
        if not d.is_dir():
            continue
        yf = d / "component.yaml"
        if not yf.exists():
            continue
        m = _yaml.safe_load(yf.read_text())
        install = m.get("install") or {}
        if "script" not in install or install["script"] is None:
            continue

        name = d.name
        meta = m.get("metadata", {})
        title = meta.get("description", name)
        version = meta.get("version", "")
        comp_written = 0

        for filename, (specific, fallback, label) in SCRIPTS.items():
            body = specific.get(name)

            if body is None:
                if fallback is None:
                    # install.sh: no body = skip entirely
                    print(f"  [!] {name}/install.sh: no body defined — skipping component")
                    total_skipped += 1
                    break
                # upgrade/uninstall/validate: use the default
                body = fallback(name)

            content = header(title, label, version) + body
            target = d / filename

            if args.dry_run:
                print(f"  [dry] {name}/{filename} ({len(content)} bytes)")
            else:
                target.write_text(content)
                target.chmod(target.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
            comp_written += 1

        total_written += comp_written

    action = "Would write" if args.dry_run else "Wrote"
    scripts_per = len(SCRIPTS)
    comps = total_written // scripts_per
    print(f"\n{action} {total_written} scripts ({comps} components × {scripts_per} lifecycle scripts).")
    if total_skipped:
        print(f"Skipped {total_skipped} components (no install body defined).")


if __name__ == "__main__":
    main()

