#!/usr/bin/env bash
# tmux workspace layouts + key bindings — install
# Generated by tools/generate_scripts.py
set -euo pipefail

# ── helpers ───────────────────────────────────────────────────────────────────
_g="\033[0;32m" _y="\033[0;33m" _r="\033[0;31m" _b="\033[0m"
info()    { echo -e "${_g}[sindri]${_b} $*"; }
warn()    { echo -e "${_y}[warn]${_b}  $*"; }
die()     { echo -e "${_r}[error]${_b} $*" >&2; exit 1; }
has()     { command -v "$1" &>/dev/null; }
require() { has "$1" || die "Required: $1 — install it before running this script."; }

# ── version contract (ADR-024) ─────────────────────────────────────────────────
# SINDRI_COMPONENT_VERSION: injected by the sindri CLI before invoking this script.
# Carries the exact version declared in registry component.yaml.
# Scripts MUST exit 0 without side effects when already at target version.
WANT="${SINDRI_COMPONENT_VERSION:-1.0.0}"

# Extract semver from binary's version output
version_of() {
    "${1}" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || "${1}" version  2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || echo ""
}

# Return 0 (true) and print status if $1 binary is already at $WANT.
# Return 1 (false) and print upgrade/install intent otherwise.
at_version() {
    local bin="$1" have
    have=$(version_of "$bin")
    if [[ -n "$WANT" && ( "$have" == "$WANT"* || "$have" == *"$WANT"* ) ]]; then
        info "$bin $WANT already installed. Nothing to do."
        return 0
    fi
    [[ -n "$have" ]] && info "$bin: $have → $WANT" || info "Installing $bin $WANT…"
    return 1
}

info "Installing tmux workspace layouts and helpers…"

# Ensure tmux is present
if ! has tmux; then
    case "$(uname -s)" in
        Darwin) has brew && brew install tmux || die "Install tmux: brew install tmux" ;;
        Linux)  has apt-get && sudo apt-get install -y tmux \
                || has dnf && sudo dnf install -y tmux \
                || die "Install tmux via your package manager." ;;
    esac
fi

TMUX_CONF="$HOME/.tmux.conf"
if [[ ! -f "$TMUX_CONF" ]]; then
    cat > "$TMUX_CONF" <<'EOF'
# sindri tmux defaults
set -g default-terminal "screen-256color"
set -g history-limit 50000
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display "Config reloaded."
EOF
    info "Created ~/.tmux.conf with sensible defaults."
else
    warn "~/.tmux.conf already exists — not overwriting."
fi

# Install tmux Plugin Manager (optional, idempotent)
TPM_DIR="$HOME/.tmux/plugins/tpm"
if [[ ! -d "$TPM_DIR" ]]; then
    require git
    git clone --depth 1 https://github.com/tmux-plugins/tpm "$TPM_DIR" 2>/dev/null \
        && info "tmux Plugin Manager installed. Start tmux and press prefix+I to install plugins."
fi

has tmux && info "tmux $(tmux -V) ready." || die "tmux not found."
