#!/usr/bin/env bash
# tmux workspace layouts + key bindings — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing tmux workspace layouts and helpers…"

# Ensure tmux is present
if ! has tmux; then
    case "$(uname -s)" in
        Darwin) has brew && brew install tmux || die "Install tmux: brew install tmux" ;;
        Linux)  has apt-get && sudo apt-get install -y tmux \
                || has dnf && sudo dnf install -y tmux \
                || die "Install tmux via your package manager." ;;
    esac
fi

TMUX_CONF="$HOME/.tmux.conf"
if [[ ! -f "$TMUX_CONF" ]]; then
    cat > "$TMUX_CONF" <<'EOF'
# sindri tmux defaults
set -g default-terminal "screen-256color"
set -g history-limit 50000
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind r source-file ~/.tmux.conf \; display "Config reloaded."
EOF
    info "Created ~/.tmux.conf with sensible defaults."
else
    warn "~/.tmux.conf already exists — not overwriting."
fi

# Install tmux Plugin Manager (optional, idempotent)
TPM_DIR="$HOME/.tmux/plugins/tpm"
if [[ ! -d "$TPM_DIR" ]]; then
    require git
    git clone --depth 1 https://github.com/tmux-plugins/tpm "$TPM_DIR" 2>/dev/null \
        && info "tmux Plugin Manager installed. Start tmux and press prefix+I to install plugins."
fi

has tmux && info "tmux $(tmux -V) ready." || die "tmux not found."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
