#!/usr/bin/env bash
# tmux workspace layouts + key bindings — uninstall
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Removing Sindri tmux workspace configuration…"
read -rp "Remove ~/.tmux.conf? [y/N] " ans
[[ "$ans" =~ ^[Yy]$ ]] && rm -f "$HOME/.tmux.conf" && info "~/.tmux.conf removed." || info "Skipped."
read -rp "Remove tmux Plugin Manager (~/.tmux/plugins/tpm)? [y/N] " ans
[[ "$ans" =~ ^[Yy]$ ]] && rm -rf "$HOME/.tmux/plugins/tpm" || info "TPM retained."
info "tmux-workspace uninstalled (tmux itself not removed)."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
