#!/usr/bin/env bash
# Context7 MCP server registration — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Registering Context7 MCP server with Claude Code…"
require npx
require claude

if claude mcp list 2>/dev/null | grep -q "context7"; then
    warn "Context7 MCP server already registered. Skipping."
    exit 0
fi

info "Adding Context7 MCP server…"
claude mcp add context7 --scope user -- npx -y @upstash/context7-mcp \
    || die "Failed to register Context7 MCP server."

info "Context7 MCP server registered."
info "Verify with: claude mcp list"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
