#!/usr/bin/env bash
# Context7 MCP server registration — validate
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Validating context7-mcp…"
require context7-mcp
context7-mcp --version >/dev/null 2>&1 || die "context7-mcp not responding."
info "context7-mcp OK"
sindri::emit phase-complete '"change":false'
exit 0

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
