#!/usr/bin/env bash
# Apache Guacamole local stack — install
# Generated by tools/generate_scripts.py
set -euo pipefail

# ── helpers ───────────────────────────────────────────────────────────────────
_g="\033[0;32m" _y="\033[0;33m" _r="\033[0;31m" _b="\033[0m"
info()    { echo -e "${_g}[sindri]${_b} $*"; }
warn()    { echo -e "${_y}[warn]${_b}  $*"; }
die()     { echo -e "${_r}[error]${_b} $*" >&2; exit 1; }
has()     { command -v "$1" &>/dev/null; }
require() { has "$1" || die "Required: $1 — install it before running this script."; }

# ── version contract (ADR-024) ─────────────────────────────────────────────────
# SINDRI_COMPONENT_VERSION: injected by the sindri CLI before invoking this script.
# Carries the exact version declared in registry component.yaml.
# Scripts MUST exit 0 without side effects when already at target version.
WANT="${SINDRI_COMPONENT_VERSION:-1.5.5}"

# Extract semver from binary's version output
version_of() {
    "${1}" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || "${1}" version  2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || echo ""
}

# Return 0 (true) and print status if $1 binary is already at $WANT.
# Return 1 (false) and print upgrade/install intent otherwise.
at_version() {
    local bin="$1" have
    have=$(version_of "$bin")
    if [[ -n "$WANT" && ( "$have" == "$WANT"* || "$have" == *"$WANT"* ) ]]; then
        info "$bin $WANT already installed. Nothing to do."
        return 0
    fi
    [[ -n "$have" ]] && info "$bin: $have → $WANT" || info "Installing $bin $WANT…"
    return 1
}

info "Installing Apache Guacamole (Docker-based)…"
require docker

GUAC_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/sindri/guacamole"
mkdir -p "$GUAC_DIR"

# Write user-mapping if absent (single local account)
if [[ ! -f "$GUAC_DIR/user-mapping.xml" ]]; then
    cat > "$GUAC_DIR/user-mapping.xml" <<'EOF'
<user-mapping>
    <authorize username="admin" password="admin" encoding="plain">
        <connection name="local-desktop">
            <protocol>vnc</protocol>
            <param name="hostname">localhost</param>
            <param name="port">5901</param>
        </connection>
    </authorize>
</user-mapping>
EOF
    info "Created default user-mapping.xml (change the password before use)."
fi

# Launch guacamole + guacd
if docker ps --format '{{.Names}}' 2>/dev/null | grep -q sindri-guacd; then
    warn "Guacamole is already running. Skipping."
else
    info "Starting guacd (daemon)…"
    docker run -d --name sindri-guacd --restart unless-stopped \
        guacamole/guacd \
        || die "Failed to start guacd."

    info "Starting Guacamole web app…"
    docker run -d --name sindri-guacamole --restart unless-stopped \
        --link sindri-guacd:guacd \
        -v "$GUAC_DIR/user-mapping.xml:/etc/guacamole/user-mapping.xml:ro" \
        -e GUACD_HOSTNAME=guacd \
        -p 8080:8080 \
        guacamole/guacamole \
        || die "Failed to start Guacamole."
fi

info "Guacamole: http://localhost:8080/guacamole  (admin/admin)"
warn "Change the default password immediately after first login."
