#!/usr/bin/env bash
# Ralph — personal coding agent — install
# Generated by tools/generate_scripts.py
set -euo pipefail

# ── helpers ───────────────────────────────────────────────────────────────────
_g="\033[0;32m" _y="\033[0;33m" _r="\033[0;31m" _b="\033[0m"
info()    { echo -e "${_g}[sindri]${_b} $*"; }
warn()    { echo -e "${_y}[warn]${_b}  $*"; }
die()     { echo -e "${_r}[error]${_b} $*" >&2; exit 1; }
has()     { command -v "$1" &>/dev/null; }
require() { has "$1" || die "Required: $1 — install it before running this script."; }

# ── version contract (ADR-024) ─────────────────────────────────────────────────
# SINDRI_COMPONENT_VERSION: injected by the sindri CLI before invoking this script.
# Carries the exact version declared in registry component.yaml.
# Scripts MUST exit 0 without side effects when already at target version.
WANT="${SINDRI_COMPONENT_VERSION:-1.0.0}"

# Extract semver from binary's version output
version_of() {
    "${1}" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || "${1}" version  2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || echo ""
}

# Return 0 (true) and print status if $1 binary is already at $WANT.
# Return 1 (false) and print upgrade/install intent otherwise.
at_version() {
    local bin="$1" have
    have=$(version_of "$bin")
    if [[ -n "$WANT" && ( "$have" == "$WANT"* || "$have" == *"$WANT"* ) ]]; then
        info "$bin $WANT already installed. Nothing to do."
        return 0
    fi
    [[ -n "$have" ]] && info "$bin: $have → $WANT" || info "Installing $bin $WANT…"
    return 1
}

info "Installing Ralph — personal coding agent…"
require claude
require node

# Ensure Claude Code is configured
if ! claude --version &>/dev/null; then
    die "Claude Code is required. Install with: npm install -g @anthropic-ai/claude-code"
fi

# Ralph is a configuration layer on top of Claude Code
RALPH_DIR="$HOME/.config/sindri/ralph"
mkdir -p "$RALPH_DIR"

cat > "$RALPH_DIR/config.yaml" <<'EOF'
# Ralph configuration
agent: ralph
model: claude-opus-4-7
tools:
  - bash
  - read
  - write
  - edit
memory: persistent
auto_compact: true
EOF

info "Ralph configured at $RALPH_DIR/config.yaml"
info "Start a Ralph session: claude --config $RALPH_DIR/config.yaml"
