#!/usr/bin/env bash
# Docker Engine (apt/dnf + post-install config) — install
# Generated by tools/generate_scripts.py
set -euo pipefail

# ── helpers ───────────────────────────────────────────────────────────────────
_g="\033[0;32m" _y="\033[0;33m" _r="\033[0;31m" _b="\033[0m"
info()    { echo -e "${_g}[sindri]${_b} $*"; }
warn()    { echo -e "${_y}[warn]${_b}  $*"; }
die()     { echo -e "${_r}[error]${_b} $*" >&2; exit 1; }
has()     { command -v "$1" &>/dev/null; }
require() { has "$1" || die "Required: $1 — install it before running this script."; }

# ── version contract (ADR-024) ─────────────────────────────────────────────────
# SINDRI_COMPONENT_VERSION: injected by the sindri CLI before invoking this script.
# Carries the exact version declared in registry component.yaml.
# Scripts MUST exit 0 without side effects when already at target version.
WANT="${SINDRI_COMPONENT_VERSION:-27.3.0}"

# Extract semver from binary's version output
version_of() {
    "${1}" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || "${1}" version  2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || echo ""
}

# Return 0 (true) and print status if $1 binary is already at $WANT.
# Return 1 (false) and print upgrade/install intent otherwise.
at_version() {
    local bin="$1" have
    have=$(version_of "$bin")
    if [[ -n "$WANT" && ( "$have" == "$WANT"* || "$have" == *"$WANT"* ) ]]; then
        info "$bin $WANT already installed. Nothing to do."
        return 0
    fi
    [[ -n "$have" ]] && info "$bin: $have → $WANT" || info "Installing $bin $WANT…"
    return 1
}

at_version docker && exit 0
info "Configuring Docker…"

# Add current user to docker group for rootless access
if ! groups "${USER:-developer}" 2>/dev/null | grep -q docker; then
    info "Adding ${USER:-developer} to docker group…"
    sudo usermod -aG docker "${USER:-developer}" \
        && warn "Group change takes effect on next login."
fi

# Write sensible daemon defaults if not already configured
DAEMON_JSON="/etc/docker/daemon.json"
if [[ ! -f "$DAEMON_JSON" ]]; then
    sudo mkdir -p /etc/docker
    sudo tee "$DAEMON_JSON" > /dev/null <<'EOF'
{
    "storage-driver": "overlay2",
    "data-root": "/var/lib/docker",
    "log-level": "warn",
    "live-restore": true
}
EOF
    info "Created $DAEMON_JSON with overlay2 storage driver."
fi

# Start daemon if not running (non-systemd container environments)
if ! docker info &>/dev/null; then
    info "Starting Docker daemon…"
    sudo nohup dockerd > "${HOME}/.local/state/dockerd.log" 2>&1 &
    for i in {1..15}; do
        docker info &>/dev/null && break || sleep 1
    done
fi

docker info &>/dev/null && info "Docker daemon reachable." \
                        || warn "Docker daemon may still be starting. Try: sudo docker info"
