#!/usr/bin/env bash
# Docker Engine (apt/dnf + post-install config) — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

at_version docker && exit 0
info "Configuring Docker…"

# Add current user to docker group for rootless access
if ! groups "${USER:-developer}" 2>/dev/null | grep -q docker; then
    info "Adding ${USER:-developer} to docker group…"
    sudo usermod -aG docker "${USER:-developer}" \
        && warn "Group change takes effect on next login."
fi

# Write sensible daemon defaults if not already configured
DAEMON_JSON="/etc/docker/daemon.json"
if [[ ! -f "$DAEMON_JSON" ]]; then
    sudo mkdir -p /etc/docker
    sudo tee "$DAEMON_JSON" > /dev/null <<'EOF'
{
    "storage-driver": "overlay2",
    "data-root": "/var/lib/docker",
    "log-level": "warn",
    "live-restore": true
}
EOF
    info "Created $DAEMON_JSON with overlay2 storage driver."
fi

# Start daemon if not running (non-systemd container environments)
if ! docker info &>/dev/null; then
    info "Starting Docker daemon…"
    sudo nohup dockerd > "${HOME}/.local/state/dockerd.log" 2>&1 &
    for i in {1..15}; do
        docker info &>/dev/null && break || sleep 1
    done
fi

docker info &>/dev/null && info "Docker daemon reachable." \
                        || warn "Docker daemon may still be starting. Try: sudo docker info"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
