#!/usr/bin/env bash
# Docker Engine (apt/dnf + post-install config) — uninstall
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Stopping Sindri Docker containers…"
docker stop sindri-prometheus sindri-grafana 2>/dev/null || true
docker rm   sindri-prometheus sindri-grafana 2>/dev/null || true
info "Sindri Docker monitoring containers removed."
warn "Docker Engine itself was installed by the system and is NOT removed by this script."
warn "To uninstall Docker Engine: sudo apt-get remove docker-ce docker-ce-cli containerd.io"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
