#!/usr/bin/env bash
# GitHub Spec Kit — spec-driven development — install
# Generated by tools/generate_scripts.py
set -euo pipefail

# ── helpers ───────────────────────────────────────────────────────────────────
_g="\033[0;32m" _y="\033[0;33m" _r="\033[0;31m" _b="\033[0m"
info()    { echo -e "${_g}[sindri]${_b} $*"; }
warn()    { echo -e "${_y}[warn]${_b}  $*"; }
die()     { echo -e "${_r}[error]${_b} $*" >&2; exit 1; }
has()     { command -v "$1" &>/dev/null; }
require() { has "$1" || die "Required: $1 — install it before running this script."; }

# ── version contract (ADR-024) ─────────────────────────────────────────────────
# SINDRI_COMPONENT_VERSION: injected by the sindri CLI before invoking this script.
# Carries the exact version declared in registry component.yaml.
# Scripts MUST exit 0 without side effects when already at target version.
WANT="${SINDRI_COMPONENT_VERSION:-1.0.0}"

# Extract semver from binary's version output
version_of() {
    "${1}" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || "${1}" version  2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || echo ""
}

# Return 0 (true) and print status if $1 binary is already at $WANT.
# Return 1 (false) and print upgrade/install intent otherwise.
at_version() {
    local bin="$1" have
    have=$(version_of "$bin")
    if [[ -n "$WANT" && ( "$have" == "$WANT"* || "$have" == *"$WANT"* ) ]]; then
        info "$bin $WANT already installed. Nothing to do."
        return 0
    fi
    [[ -n "$have" ]] && info "$bin: $have → $WANT" || info "Installing $bin $WANT…"
    return 1
}

info "Installing GitHub Spec Kit (spec-driven development)…"
require python3

# Install via pip/uv
if has uv; then
    uv tool install spec-kit 2>/dev/null || true
elif has pip3; then
    pip3 install --user spec-kit 2>/dev/null || true
fi

# Fallback: clone from GitHub if not available as package
if ! has spec; then
    require git
    SPEC_DIR="$HOME/.local/share/sindri/spec-kit"
    if [[ -d "$SPEC_DIR" ]]; then
        info "Updating spec-kit…"
        git -C "$SPEC_DIR" pull --ff-only 2>/dev/null || true
    else
        git clone --depth 1 https://github.com/sindri-dev/spec-kit "$SPEC_DIR" 2>/dev/null \
            || warn "Could not clone spec-kit. Install manually."
    fi
    [[ -f "$SPEC_DIR/spec" ]] && { cp "$SPEC_DIR/spec" "$HOME/.local/bin/spec"; chmod +x "$HOME/.local/bin/spec"; }
fi

has spec && info "spec-kit installed: $(spec --version 2>/dev/null || echo ok)" \
         || warn "spec-kit installed but 'spec' not in PATH. Add ~/.local/bin to PATH."
