#!/usr/bin/env bash
# Supabase CLI (docker-backed local dev) — install
# Generated by tools/generate_scripts.py
set -euo pipefail

# ── helpers ───────────────────────────────────────────────────────────────────
_g="\033[0;32m" _y="\033[0;33m" _r="\033[0;31m" _b="\033[0m"
info()    { echo -e "${_g}[sindri]${_b} $*"; }
warn()    { echo -e "${_y}[warn]${_b}  $*"; }
die()     { echo -e "${_r}[error]${_b} $*" >&2; exit 1; }
has()     { command -v "$1" &>/dev/null; }
require() { has "$1" || die "Required: $1 — install it before running this script."; }

# ── version contract (ADR-024) ─────────────────────────────────────────────────
# SINDRI_COMPONENT_VERSION: injected by the sindri CLI before invoking this script.
# Carries the exact version declared in registry component.yaml.
# Scripts MUST exit 0 without side effects when already at target version.
WANT="${SINDRI_COMPONENT_VERSION:-1.200.0}"

# Extract semver from binary's version output
version_of() {
    "${1}" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || "${1}" version  2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || echo ""
}

# Return 0 (true) and print status if $1 binary is already at $WANT.
# Return 1 (false) and print upgrade/install intent otherwise.
at_version() {
    local bin="$1" have
    have=$(version_of "$bin")
    if [[ -n "$WANT" && ( "$have" == "$WANT"* || "$have" == *"$WANT"* ) ]]; then
        info "$bin $WANT already installed. Nothing to do."
        return 0
    fi
    [[ -n "$have" ]] && info "$bin: $have → $WANT" || info "Installing $bin $WANT…"
    return 1
}

info "Installing Supabase CLI…"

at_version supabase && exit 0

case "$(uname -s)" in
    Darwin)
        require brew
        brew install supabase/tap/supabase ;;
    Linux)
        require curl
        # Download latest binary from GitHub releases
        ARCH="$(uname -m)"
        [[ "$ARCH" == "x86_64" ]]  && ARCH="linux_amd64"
        [[ "$ARCH" == "aarch64" ]] && ARCH="linux_arm64"
        LATEST=$(curl -sSf https://api.github.com/repos/supabase/cli/releases/latest \
                    | grep '"tag_name"' | head -1 | grep -oE 'v[0-9.]+')
        [[ -z "$LATEST" ]] && die "Could not determine latest Supabase CLI version."
        URL="https://github.com/supabase/cli/releases/download/${LATEST}/supabase_${ARCH}.tar.gz"
        mkdir -p "$HOME/.local/bin"
        curl -fsSL "$URL" | tar -xz -C "$HOME/.local/bin" supabase
        chmod +x "$HOME/.local/bin/supabase" ;;
    *)
        die "Unsupported OS." ;;
esac

has supabase && info "Supabase CLI $(supabase --version 2>/dev/null) ready." \
            || die "Supabase CLI not found after install."
info "Start local dev: supabase start"
