extends: default
rules:
  line-length:
    max: 225
    level: warning # Keep as warning, not error

  comments:
    min-spaces-from-content: 1

  document-start: disable

  truthy:
    allowed-values: ["true", "false", "on", "off"] # Allow 'on' for GitHub Actions

  new-line-at-end-of-file: enable
