# ============================================================================
# Sindri Makefile — Master Orchestrator
# ============================================================================
# Delegates to modular sub-makefiles in makefiles/
#
# Quick Start:
#   make help            - Show all available targets
#   make deps-check      - Verify all dependencies
#   make ci              - Run full CI (v2 + v3 + console)
#   make v3-build        - Build Rust binary
#   make v2-test         - Test v2 components
#   make console-build   - Build Console (API + Web)
# ============================================================================

include makefiles/common.mk
include makefiles/cross-cutting.mk
include makefiles/v2.mk
include makefiles/v3.mk
include makefiles/console-agent.mk
include makefiles/console.mk
include makefiles/faq.mk

.DEFAULT_GOAL := help

.PHONY: help
help:
	@echo "$(BOLD)$(BLUE)╔════════════════════════════════════════════════════════════════════╗$(RESET)"
	@echo "$(BOLD)$(BLUE)║                          Sindri Makefile                           ║$(RESET)"
	@echo "$(BOLD)$(BLUE)╚════════════════════════════════════════════════════════════════════╝$(RESET)"
	@echo ""
	@echo "$(BOLD)Quick Start:$(RESET)"
	@echo "  make deps-check        - Check all dependencies"
	@echo "  make ci                - Run full CI pipeline (v2 + v3 + console)"
	@echo "  make v3-build          - Build Rust binary (release)"
	@echo "  make v2-test           - Run v2 unit tests"
	@echo "  make format            - Format all code (Prettier + Cargo + gofmt)"
	@echo "  make lint              - Run all linters"
	@echo "  make console-build     - Build Console (API + Web)"
	@echo "  make console-agent-build - Build Go agent binary"
	@echo ""
	@echo "$(BOLD)$(BLUE)═══ Dependency Management ═══════════════════════════════════════════$(RESET)"
	@echo "  deps-check             - Check all dependencies (required + optional)"
	@echo "  deps-check-required    - Check only required dependencies"
	@echo "  deps-check-optional    - Check only optional dependencies"
	@echo "  deps-upgrade           - Upgrade npm and cargo dependencies"
	@echo "  deps-upgrade-npm       - Upgrade npm dependencies"
	@echo "  deps-upgrade-cargo     - Upgrade cargo dependencies"
	@echo ""
	@echo "$(BOLD)$(BLUE)═══ Formatting & Validation ═════════════════════════════════════════$(RESET)"
	@echo "  format                 - Format all files (Prettier + Cargo fmt + gofmt)"
	@echo "  format-check           - Check formatting without changes"
	@echo "  links-check            - Check markdown links (local files only)"
	@echo "  links-check-external   - Check external HTTP/HTTPS links"
	@echo "  links-check-all        - Check all links (local + external)"
	@echo "  audit                  - Run security audits (npm + cargo + pnpm + govulncheck)"
	@echo ""
	@echo "$(BOLD)$(BLUE)═══ Linting ═════════════════════════════════════════════════════════$(RESET)"
	@echo "  lint                   - Run all linters (YAML + MD + JSON + Rust)"
	@echo "  lint-yaml              - Lint all YAML files (strict)"
	@echo "  lint-markdown          - Lint all markdown files"
	@echo "  lint-json              - Lint all JSON files"
	@echo "  lint-rust              - Lint Rust code with clippy"
	@echo "  lint-html              - Lint HTML files (if any exist)"
	@echo ""
	@echo "$(BOLD)$(BLUE)═══ V2 (Bash/Docker) Targets ════════════════════════════════════════$(RESET)"
	@echo "  v2-validate            - Validate v2 code (YAML + shell + markdown)"
	@echo "  v2-validate-yaml       - Validate v2 YAML files"
	@echo "  v2-validate-shell      - Validate v2 shell scripts (shellcheck)"
	@echo "  v2-validate-markdown   - Validate v2 markdown files"
	@echo "  v2-lint                - Lint v2 code (strict mode)"
	@echo "  v2-test                - Run v2 unit tests"
	@echo "  v2-test-extensions     - Test v2 extensions"
	@echo "  v2-build               - Build v2 (alias for v2-docker-build)"
	@echo "  v2-docker-build        - Build v2 Docker image (local tag)"
	@echo "  v2-docker-build-latest - Build v2 Docker image (latest tag)"
	@echo "  v2-docker-build-nocache - Build v2 Docker image (no cache)"
	@echo "  v2-config-init         - Initialize sindri.yaml"
	@echo "  v2-config-validate     - Validate sindri.yaml"
	@echo "  v2-extensions-list     - List available extensions"
	@echo "  v2-extensions-install  - Install extensions interactively"
	@echo "  v2-extensions-search   - Search for extensions"
	@echo "  v2-profiles-list       - List extension profiles"
	@echo "  v2-deploy              - Deploy v2 to provider"
	@echo "  v2-connect             - Connect to v2 deployment"
	@echo ""
	@echo "$(BOLD)$(BLUE)═══ V3 (Rust) Targets ═══════════════════════════════════════════════$(RESET)"
	@echo "  v3-build               - Build Rust binary (release mode)"
	@echo "  v3-build-debug         - Build Rust binary (debug mode)"
	@echo "  v3-check               - Fast compile check"
	@echo "  v3-test                - Run Rust tests"
	@echo "  v3-test-verbose        - Run Rust tests (verbose output)"
	@echo "  v3-test-crate          - Test one crate (use: make v3-test-crate CRATE=sindri-core)"
	@echo "  v3-validate            - Validate Rust code (fmt + clippy + YAML)"
	@echo "  v3-validate-yaml       - Validate v3 YAML files"
	@echo "  v3-validate-rust       - Validate Rust code only"
	@echo "  v3-clippy              - Run clippy linter"
	@echo "  v3-fmt                 - Format Rust code"
	@echo "  v3-fmt-check           - Check Rust formatting"
	@echo "  v3-audit               - Security audit"
	@echo "  v3-audit-fix           - Fix security vulnerabilities"
	@echo "  v3-coverage            - Run tests with coverage summary"
	@echo "  v3-coverage-html       - Coverage report (HTML in coverage/)"
	@echo "  v3-coverage-lcov       - Coverage report (LCOV for CI)"
	@echo "  v3-doc                 - Generate and open documentation"
	@echo "  v3-run                 - Run v3 binary (use: make v3-run ARGS=\"version\")"
	@echo "  v3-run-debug           - Run v3 debug binary"
	@echo "  v3-install             - Install v3 binary to ~/.cargo/bin"
	@echo "  v3-docker-build        - Build v3 Docker image (from binary, local tag)"
	@echo "  v3-docker-build-latest - Build v3 Docker image (latest tag)"
	@echo "  v3-docker-build-nocache - Build v3 Docker image (no cache)"
	@echo "  v3-docker-build-from-source - Build v3 Docker from source"
	@echo "  v3-docker-build-from-binary - Build v3 Docker from binary (default)"
	@echo "  v3-docker-build-base   - Build base image (15-20 min, once per Rust version)"
	@echo "  v3-docker-build-fast   - Fast build using base (3-5 min, recommended)"
	@echo "  v3-cycle-fast          - Fast dev cycle (3-5 min, keeps caches)"
	@echo "                           Usage: make v3-cycle-fast CONFIG=/path/to/sindri.yaml"
	@echo "  v3-cycle-clean         - Clean dev cycle (10-15 min, clears caches)"
	@echo "  v3-cycle-nuclear       - Full rebuild (40-50 min, nuclear option)"
	@echo "  v3-cycle               - Alias for v3-cycle-nuclear"
	@echo "  v3-cache-status        - Show cache usage"
	@echo "  v3-cache-clear-soft    - Clear incremental caches"
	@echo "  v3-cache-clear-medium  - Clear cargo + build cache"
	@echo "  v3-cache-clear-hard    - Clear all except base"
	@echo ""
	@echo "$(BOLD)$(BLUE)═══ Console Agent (Go) Targets ══════════════════════════════════════$(RESET)"
	@echo "  console-agent-build    - Build agent for current platform (static)"
	@echo "  console-agent-build-all - Cross-compile: linux-amd64, linux-arm64, darwin-amd64, darwin-arm64"
	@echo "  console-agent-test     - Run agent unit tests"
	@echo "  console-agent-fmt      - Format Go code (gofmt)"
	@echo "  console-agent-fmt-check - Check Go formatting without changes"
	@echo "  console-agent-vet      - Run go vet"
	@echo "  console-agent-lint     - Run golangci-lint"
	@echo "  console-agent-audit    - Vulnerability scan (govulncheck)"
	@echo "  console-agent-install  - Install sindri-agent to ~/.local/bin"
	@echo "  console-agent-clean    - Remove agent build artifacts"
	@echo "  console-agent-ci       - Full agent CI (vet + test + build-all)"
	@echo ""
	@echo "$(BOLD)$(BLUE)═══ Console Infrastructure Targets (postgres + redis) ═══════════════$(RESET)"
	@echo "  console-infra-up       - Start postgres + redis in Docker (detached)"
	@echo "  console-infra-down     - Stop infrastructure services"
	@echo "  console-infra-reset    - Destroy volumes and restart fresh"
	@echo "  console-infra-logs     - Follow infrastructure logs (Ctrl-C to stop)"
	@echo "  console-infra-status   - Show postgres + redis container status"
	@echo ""
	@echo "$(BOLD)$(BLUE)═══ Console Full-Stack Targets (all 4 services) ════════════════════$(RESET)"
	@echo "  console-stack-build    - Build API + Web Docker images"
	@echo "  console-stack-up       - Start full stack (postgres+redis+api+web)"
	@echo "  console-stack-down     - Stop full stack"
	@echo "  console-stack-logs     - Follow all service logs (Ctrl-C to stop)"
	@echo "  console-stack-status   - Show all container status"
	@echo "  console-stack-rebuild  - Rebuild images (no-cache) and restart"
	@echo ""
	@echo "$(BOLD)$(BLUE)═══ Console (TypeScript) Targets ════════════════════════════════════$(RESET)"
	@echo "  console-install        - Install pnpm dependencies"
	@echo "  console-build          - Build all Console packages (API + Web)"
	@echo "  console-dev            - Start dev servers locally (API + Web, parallel)"
	@echo "  console-dev-full       - Start infra in Docker then local dev servers"
	@echo "  console-test           - Run all Console tests"
	@echo "  console-test-coverage  - Run tests with coverage report"
	@echo "  console-lint           - Run ESLint on all packages"
	@echo "  console-typecheck      - Run TypeScript type checking"
	@echo "  console-fmt            - Format TypeScript/CSS/JSON with Prettier"
	@echo "  console-fmt-check      - Check Prettier formatting without changes"
	@echo "  console-audit          - Run pnpm security audit"
	@echo "  console-audit-fix      - Auto-fix pnpm audit issues"
	@echo "  console-upgrade        - Upgrade console dependencies (latest)"
	@echo "  console-upgrade-interactive - Interactive dependency upgrade"
	@echo "  console-clean          - Clean build artifacts"
	@echo "  console-db-migrate     - Run Prisma migrations (dev)"
	@echo "  console-db-migrate-deploy - Deploy migrations (production-style)"
	@echo "  console-db-generate    - Generate Prisma client"
	@echo "  console-db-seed        - Seed the database"
	@echo "  console-db-reset       - Reset database (destructive)"
	@echo "  console-db-studio      - Open Prisma Studio (browser UI)"
	@echo ""
	@echo "$(BOLD)Quick examples:$(RESET)"
	@echo "  make console-build                   - Build API + Web"
	@echo "  make console-agent-build             - Build Go agent (current platform)"
	@echo "  make console-agent-build-all         - Cross-compile all platforms"
	@echo "  make console-ci                      - Full Console CI pipeline"
	@echo ""
	@echo "$(BOLD)$(BLUE)═══ FAQ Static Site Targets ═════════════════════════════════════════$(RESET)"
	@echo "  faq-validate           - Validate FAQ data schema (jq)"
	@echo "  faq-build              - Generate self-contained index.html from sources"
	@echo "  faq-preview            - Build and open index.html locally in browser"
	@echo "  faq-docker-build       - Build FAQ Docker image (nginx:alpine)"
	@echo "  faq-docker-run         - Run FAQ Docker image on localhost:8080"
	@echo "                           Override port: make faq-docker-run FAQ_LOCAL_PORT=9090"
	@echo "  faq-docker-stop        - Stop running FAQ container"
	@echo "  faq-deploy             - Validate + build + deploy to Fly.io"
	@echo "  faq-status             - Show Fly.io app status"
	@echo "  faq-logs               - Follow Fly.io deployment logs"
	@echo "  faq-open               - Open https://sindri-faq.fly.dev in browser"
	@echo "  faq-ci                 - Validate + build (CI gate, no deploy)"
	@echo ""
	@echo "$(BOLD)$(BLUE)═══ CI/CD Targets ═══════════════════════════════════════════════════$(RESET)"
	@echo "  ci                     - Run full CI (v2 + v3 + console)"
	@echo "  v2-ci                  - Run v2 CI pipeline"
	@echo "  v3-ci                  - Run v3 CI pipeline (validate + test + build)"
	@echo "  v3-quality             - Full quality gate (fmt + clippy + test + audit + coverage)"
	@echo "  console-agent-ci       - Console agent CI (vet + test + build-all)"
	@echo "  console-ci             - Full Console CI (agent + TypeScript: fmt-check + lint + typecheck + test + build)"
	@echo ""
	@echo "$(BOLD)$(BLUE)═══ Utility ═════════════════════════════════════════════════════════$(RESET)"
	@echo "  clean                  - Clean all build artifacts"
	@echo "  v2-clean               - Clean v2 Docker images"
	@echo "  v3-clean               - Clean v3 Rust artifacts"
	@echo "  console-agent-clean    - Clean Go agent build artifacts"
	@echo "  console-clean          - Clean Console TypeScript artifacts"
	@echo ""
