#!/usr/bin/env bash
# Pulumi IaC — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing Pulumi IaC CLI…"
require curl

at_version pulumi && exit 0

info "Downloading Pulumi installer…"
curl -fsSL https://get.pulumi.com | sh || die "Pulumi install failed."

# Ensure PATH includes ~/.pulumi/bin
export PATH="$HOME/.pulumi/bin:$PATH"
has pulumi && info "Pulumi $(pulumi version 2>/dev/null) installed." \
          || die "Pulumi not found after install."
info "Create a project: pulumi new"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
