# Provider Test Configuration
# Defines test parameters for each provider

providers:
  docker:
    enabled: true
    test_suites:
      - smoke
      - integration
    timeout_minutes: 15
    resources:
      memory: 2GB
      cpus: 2
    test_commands:
      - sindri --version
      - extension-manager list
      - extension-manager list-profiles
    extensions_to_test:
      - nodejs
      - python
      - docker

  fly:
    enabled: true
    test_suites:
      - smoke
      - integration
      - persistence
    timeout_minutes: 20
    regions:
      - sjc
      - ord
      - ams
    vm_sizes:
      small: shared-cpu-1x
      medium: shared-cpu-2x
      large: dedicated-cpu-2x
    test_commands:
      - sindri --version
      - extension-manager list
      - df -h /workspace
    extensions_to_test:
      - nodejs
      - python
      - golang
      - terraform

  devpod-aws:
    enabled: true
    test_suites:
      - smoke
      - integration
    timeout_minutes: 30
    regions:
      - us-west-2
      - us-east-1
    instance_types:
      small: t3.small
      medium: t3.medium
      large: t3.large
    use_spot: true
    disk_size: 40
    test_commands:
      - sindri config validate
      - extension-manager status nodejs
    extensions_to_test:
      - nodejs
      - aws-cli
      - terraform

  devpod-gcp:
    enabled: true
    test_suites:
      - smoke
      - integration
    timeout_minutes: 30
    zones:
      - us-central1-a
      - europe-west1-b
    machine_types:
      small: e2-small
      medium: e2-medium
      large: e2-standard-4
    disk_size: 50
    test_commands:
      - sindri --help
      - extension-manager validate-all
    extensions_to_test:
      - nodejs
      - gcloud
      - kubernetes-tools

  devpod-azure:
    enabled: true
    test_suites:
      - smoke
      - integration
    timeout_minutes: 30
    locations:
      - eastus
      - westeurope
    vm_sizes:
      small: Standard_B1s
      medium: Standard_B2s
      large: Standard_D2s_v3
    disk_size: 30
    test_commands:
      - sindri config init
      - extension-manager install python
    extensions_to_test:
      - nodejs
      - azure-cli
      - dotnet

  devpod-do:
    enabled: true
    test_suites:
      - smoke
      - integration
    timeout_minutes: 25
    regions:
      - nyc3
      - sfo3
      - ams3
    sizes:
      small: s-1vcpu-1gb
      medium: s-2vcpu-4gb
      large: s-4vcpu-8gb
    test_commands:
      - sindri --version
      - extension-manager list
    extensions_to_test:
      - nodejs
      - docker
      - kubectl

  kubernetes:
    enabled: true
    test_suites:
      - smoke
      - integration
    timeout_minutes: 20
    namespaces:
      - devpod
      - sindri-test
    storage_class: standard
    resource_limits:
      memory: 2Gi
      cpu: 2
    test_commands:
      - sindri config validate
      - kubectl version --client
    extensions_to_test:
      - kubernetes-tools
      - helm
      - kubectl

  ssh:
    enabled: false  # Requires SSH server setup
    test_suites:
      - smoke
    timeout_minutes: 15
    ssh_host: test-server.example.com
    ssh_user: developer
    test_commands:
      - sindri --version
      - whoami
    extensions_to_test:
      - nodejs

# Test profiles for different scenarios
test_profiles:
  minimal:
    description: Minimal test suite for quick validation
    providers:
      - docker
    test_suites:
      - smoke
    extensions:
      - nodejs

  standard:
    description: Standard test suite for PR validation
    providers:
      - docker
      - fly
    test_suites:
      - smoke
      - integration
    extensions:
      - nodejs
      - python
      - docker

  comprehensive:
    description: Comprehensive test suite for main branch
    providers:
      - docker
      - fly
      - devpod-aws
      - kubernetes
    test_suites:
      - smoke
      - integration
      - persistence
    extensions:
      - nodejs
      - python
      - golang
      - terraform
      - kubernetes-tools

  nightly:
    description: Nightly test suite covering all providers
    providers:
      - docker
      - fly
      - devpod-aws
      - devpod-gcp
      - devpod-azure
      - devpod-do
      - kubernetes
    test_suites:
      - smoke
      - integration
      - persistence
      - stress
    extensions: all

# Test scenarios for integration testing
test_scenarios:
  basic_deployment:
    description: Basic deployment and verification
    steps:
      - deploy_application
      - verify_health
      - test_cli_commands
      - cleanup

  extension_installation:
    description: Test extension installation and validation
    steps:
      - deploy_application
      - install_extension
      - validate_extension
      - test_idempotency
      - cleanup

  persistence_test:
    description: Test data persistence across restarts
    steps:
      - deploy_application
      - create_test_data
      - restart_application
      - verify_data_persistence
      - cleanup

  multi_extension:
    description: Test multiple extension installation
    steps:
      - deploy_application
      - install_profile
      - validate_all_extensions
      - test_extension_interactions
      - cleanup

  failover_test:
    description: Test failover and recovery
    steps:
      - deploy_application
      - simulate_failure
      - verify_recovery
      - test_functionality
      - cleanup

# Performance benchmarks
benchmarks:
  deployment_time:
    docker: 30s
    fly: 120s
    devpod-aws: 180s
    kubernetes: 60s

  extension_install_time:
    nodejs: 30s
    python: 45s
    golang: 60s
    rust: 90s

  cold_start_time:
    docker: 5s
    fly: 15s
    devpod: 20s
    kubernetes: 10s

# Cleanup policies
cleanup_policies:
  pr_tests:
    max_age_hours: 2
    cleanup_on_failure: true
    cleanup_on_success: true

  main_tests:
    max_age_hours: 6
    cleanup_on_failure: false
    cleanup_on_success: true

  manual_deployment:
    max_age_hours: 24
    cleanup_on_failure: false
    cleanup_on_success: false

  nightly_tests:
    max_age_hours: 12
    cleanup_on_failure: true
    cleanup_on_success: true
