#!/usr/bin/env bash
# Block's Goose agent — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing Goose AI agent (Block)…"
require curl

at_version goose && exit 0

info "Fetching official Goose installer…"
CONFIGURE=false curl -fsSL \
    https://github.com/block/goose/releases/download/stable/download_cli.sh | bash \
    || die "Goose install failed."

hash -r 2>/dev/null || true
has goose || die "Goose binary not found after install."
info "Goose $(goose --version 2>/dev/null) installed."
info "Configure your LLM provider: goose configure"
info "Start a session:              goose session"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
