#!/usr/bin/env bash
# Atlassian Jira MCP server — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Registering Jira MCP server with Claude Code…"
require npx
require claude

if claude mcp list 2>/dev/null | grep -q "jira"; then
    warn "Jira MCP server already registered. Skipping."
    exit 0
fi

info "Adding Jira MCP server…"
claude mcp add jira --scope user -- npx -y @smithery/cli@latest run @sooperset/mcp-atlassian \
    || die "Failed to register Jira MCP server."

warn "Configure Jira credentials: ATLASSIAN_URL, ATLASSIAN_USER_EMAIL, ATLASSIAN_API_TOKEN"
info "Jira MCP server registered."
info "Verify with: claude mcp list"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
