#!/usr/bin/env bash
# draupnir — infra forge — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing draupnir infra forge…"
require node

npm install -g @sindri/draupnir 2>/dev/null \
    || warn "draupnir not found on npm. May need manual install from source."

has draupnir && info "draupnir installed: $(draupnir --version 2>/dev/null || echo ok)" \
             || warn "draupnir installed but not in PATH."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
