#!/usr/bin/env bash
# SDKMAN! — the software development kit manager — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing SDKMAN (Software Development Kit Manager)…"

export SDKMAN_DIR="${SDKMAN_DIR:-$HOME/.sdkman}"

if [[ -d "$SDKMAN_DIR" && -f "$SDKMAN_DIR/bin/sdkman-init.sh" ]]; then
    warn "SDKMAN already installed at $SDKMAN_DIR — updating to latest…"
    source "$SDKMAN_DIR/bin/sdkman-init.sh" 2>/dev/null || true
    sdk selfupdate force 2>/dev/null || true
    info "SDKMAN updated."
else
    info "Downloading SDKMAN from https://get.sdkman.io …"
    require curl
    curl -s "https://get.sdkman.io" | bash || die "SDKMAN install failed."
    info "SDKMAN installed."
fi

# Verify
source "$SDKMAN_DIR/bin/sdkman-init.sh" 2>/dev/null || true
has sdk && info "sdk: $(sdk version 2>/dev/null | head -1)" \
         || info "sdk function will be available in new interactive shells."

info "Run 'source ~/.bashrc' or open a new shell, then: sdk install java"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
