#!/usr/bin/env bash
# SDKMAN! — the software development kit manager — uninstall
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Uninstalling SDKMAN and all managed SDKs…"
export SDKMAN_DIR="${SDKMAN_DIR:-$HOME/.sdkman}"
[[ -d "$SDKMAN_DIR" ]] || { warn "SDKMAN not found at $SDKMAN_DIR."; exit 0; }
read -rp "This will remove ALL SDKs installed via SDKMAN. Continue? [y/N] " ans
[[ "$ans" =~ ^[Yy]$ ]] || { info "Aborted."; exit 0; }
rm -rf "$SDKMAN_DIR"
# Remove shell snippets
for rc in ~/.bashrc ~/.zshrc ~/.profile; do
    [[ -f "$rc" ]] && sed -i '/sdkman/d' "$rc" 2>/dev/null || true
done
info "SDKMAN removed."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
