#!/usr/bin/env bash
# SDKMAN! — the software development kit manager — upgrade
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Upgrading SDKMAN…"
export SDKMAN_DIR="${SDKMAN_DIR:-$HOME/.sdkman}"
source "$SDKMAN_DIR/bin/sdkman-init.sh" 2>/dev/null \
    || die "SDKMAN not installed. Run install.sh first."
sdk selfupdate force
info "SDKMAN ready: $(sdk version 2>/dev/null | head -1)"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
