#!/usr/bin/env bash
# SDKMAN! — the software development kit manager — validate
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Validating SDKMAN installation…"
export SDKMAN_DIR="${SDKMAN_DIR:-$HOME/.sdkman}"
[[ -f "$SDKMAN_DIR/bin/sdkman-init.sh" ]] || die "sdkman-init.sh not found at $SDKMAN_DIR."
source "$SDKMAN_DIR/bin/sdkman-init.sh" 2>/dev/null || true
sdk version 2>/dev/null | head -1 || die "sdk command failed."
info "SDKMAN OK: $(sdk version 2>/dev/null | head -1)"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
