#!/usr/bin/env bash
# Reasoning Toolkit (rtk) — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing Reasoning Toolkit (rtk)…"
require python3

if has uv; then
    uv tool install rtk 2>/dev/null || warn "rtk not on PyPI — trying npm…"
fi

if ! has rtk && has npm; then
    npm install -g @sindri/rtk 2>/dev/null || warn "rtk not on npm."
fi

has rtk && info "rtk installed." || warn "rtk not found on public registries. May need manual install."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
