#!/usr/bin/env bash
# Supabase CLI (docker-backed local dev) — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing Supabase CLI…"

at_version supabase && exit 0

case "$(uname -s)" in
    Darwin)
        require brew
        brew install supabase/tap/supabase ;;
    Linux)
        require curl
        # Download latest binary from GitHub releases
        ARCH="$(uname -m)"
        [[ "$ARCH" == "x86_64" ]]  && ARCH="linux_amd64"
        [[ "$ARCH" == "aarch64" ]] && ARCH="linux_arm64"
        LATEST=$(curl -sSf https://api.github.com/repos/supabase/cli/releases/latest \
                    | grep '"tag_name"' | head -1 | grep -oE 'v[0-9.]+')
        [[ -z "$LATEST" ]] && die "Could not determine latest Supabase CLI version."
        URL="https://github.com/supabase/cli/releases/download/${LATEST}/supabase_${ARCH}.tar.gz"
        mkdir -p "$HOME/.local/bin"
        curl -fsSL "$URL" | tar -xz -C "$HOME/.local/bin" supabase
        chmod +x "$HOME/.local/bin/supabase" ;;
    *)
        die "Unsupported OS." ;;
esac

has supabase && info "Supabase CLI $(supabase --version 2>/dev/null) ready." \
            || die "Supabase CLI not found after install."
info "Start local dev: supabase start"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
