#!/usr/bin/env bash
# PHP language and Composer — install
# Generated by tools/generate_scripts.py
set -euo pipefail

# ── helpers ───────────────────────────────────────────────────────────────────
_g="\033[0;32m" _y="\033[0;33m" _r="\033[0;31m" _b="\033[0m"
info()    { echo -e "${_g}[sindri]${_b} $*"; }
warn()    { echo -e "${_y}[warn]${_b}  $*"; }
die()     { echo -e "${_r}[error]${_b} $*" >&2; exit 1; }
has()     { command -v "$1" &>/dev/null; }
require() { has "$1" || die "Required: $1 — install it before running this script."; }

# ── version contract (ADR-024) ─────────────────────────────────────────────────
# SINDRI_COMPONENT_VERSION: injected by the sindri CLI before invoking this script.
# Carries the exact version declared in registry component.yaml.
# Scripts MUST exit 0 without side effects when already at target version.
WANT="${SINDRI_COMPONENT_VERSION:-8.3}"

# Extract semver from binary's version output
version_of() {
    "${1}" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || "${1}" version  2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || echo ""
}

# Return 0 (true) and print status if $1 binary is already at $WANT.
# Return 1 (false) and print upgrade/install intent otherwise.
at_version() {
    local bin="$1" have
    have=$(version_of "$bin")
    if [[ -n "$WANT" && ( "$have" == "$WANT"* || "$have" == *"$WANT"* ) ]]; then
        info "$bin $WANT already installed. Nothing to do."
        return 0
    fi
    [[ -n "$have" ]] && info "$bin: $have → $WANT" || info "Installing $bin $WANT…"
    return 1
}

info "Installing PHP and Composer…"

install_via_apt() {
    require apt-get
    sudo apt-get update -qq
    sudo apt-get install -y -qq \
        php php-cli php-common php-curl php-json php-mbstring \
        php-xml php-zip php-intl php-gd 2>/dev/null
}

install_via_dnf() {
    require dnf
    sudo dnf install -y php php-cli php-common php-curl php-json \
        php-mbstring php-xml php-zip php-intl 2>/dev/null
}

install_via_brew() {
    require brew
    brew install php
}

if has php; then
    warn "PHP already installed: $(php --version | head -1). Skipping."
else
    case "$(uname -s)" in
        Linux)
            if has apt-get;  then install_via_apt
            elif has dnf;    then install_via_dnf
            else die "Unsupported Linux package manager. Install PHP manually."
            fi ;;
        Darwin) install_via_brew ;;
        *) die "Unsupported OS." ;;
    esac
    info "PHP $(php --version 2>/dev/null | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+') installed."
fi

# Install Composer
if has composer; then
    warn "Composer already installed: $(composer --version 2>/dev/null | head -1). Skipping."
else
    info "Installing Composer…"
    require curl
    EXPECTED_CHECKSUM="$(curl -sS https://composer.github.io/installer.sig)"
    php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');"
    ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', '/tmp/composer-setup.php');")"
    [[ "$EXPECTED_CHECKSUM" == "$ACTUAL_CHECKSUM" ]] || die "Composer installer checksum mismatch."
    php /tmp/composer-setup.php --quiet --install-dir="$HOME/.local/bin" --filename=composer
    rm /tmp/composer-setup.php
    info "Composer $(composer --version 2>/dev/null | head -1) installed."
fi
