#!/usr/bin/env bash
# Google Cloud SDK — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing Google Cloud SDK…"
require curl

at_version gcloud && exit 0

# Use the official interactive-less installer
info "Downloading Google Cloud SDK installer…"
export CLOUDSDK_CORE_DISABLE_PROMPTS=1
curl -sSL https://sdk.cloud.google.com | bash -s -- --disable-prompts \
    || die "Google Cloud SDK install failed."

# Source the rc update
SDK_DIR="${CLOUDSDK_ROOT_DIR:-$HOME/google-cloud-sdk}"
[[ -f "$SDK_DIR/path.bash.inc" ]] && source "$SDK_DIR/path.bash.inc"
[[ -f "$SDK_DIR/completion.bash.inc" ]] && source "$SDK_DIR/completion.bash.inc"

has gcloud && info "gcloud: $(gcloud --version 2>/dev/null | head -1)" \
           || warn "gcloud installed; start a new shell to activate."
info "Authenticate with: gcloud auth login"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
