#!/usr/bin/env bash
# Google Cloud SDK — uninstall
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Uninstalling Google Cloud SDK…"
SDK_DIR="${CLOUDSDK_ROOT_DIR:-$HOME/google-cloud-sdk}"
[[ -d "$SDK_DIR" ]] || { warn "gcloud SDK not found at $SDK_DIR."; exit 0; }
"$SDK_DIR/bin/gcloud" components remove --quiet 2>/dev/null || true
rm -rf "$SDK_DIR"
for rc in ~/.bashrc ~/.zshrc ~/.bash_profile ~/.profile; do
    [[ -f "$rc" ]] && sed -i '/google-cloud-sdk/d' "$rc" 2>/dev/null || true
done
info "Google Cloud SDK removed."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
