#!/usr/bin/env bash
# Ollama local LLM runtime — install
# Generated by tools/generate_scripts.py
set -euo pipefail

# ── helpers ───────────────────────────────────────────────────────────────────
_g="\033[0;32m" _y="\033[0;33m" _r="\033[0;31m" _b="\033[0m"
info()    { echo -e "${_g}[sindri]${_b} $*"; }
warn()    { echo -e "${_y}[warn]${_b}  $*"; }
die()     { echo -e "${_r}[error]${_b} $*" >&2; exit 1; }
has()     { command -v "$1" &>/dev/null; }
require() { has "$1" || die "Required: $1 — install it before running this script."; }

# ── version contract (ADR-024) ─────────────────────────────────────────────────
# SINDRI_COMPONENT_VERSION: injected by the sindri CLI before invoking this script.
# Carries the exact version declared in registry component.yaml.
# Scripts MUST exit 0 without side effects when already at target version.
WANT="${SINDRI_COMPONENT_VERSION:-0.5.0}"

# Extract semver from binary's version output
version_of() {
    "${1}" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || "${1}" version  2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || echo ""
}

# Return 0 (true) and print status if $1 binary is already at $WANT.
# Return 1 (false) and print upgrade/install intent otherwise.
at_version() {
    local bin="$1" have
    have=$(version_of "$bin")
    if [[ -n "$WANT" && ( "$have" == "$WANT"* || "$have" == *"$WANT"* ) ]]; then
        info "$bin $WANT already installed. Nothing to do."
        return 0
    fi
    [[ -n "$have" ]] && info "$bin: $have → $WANT" || info "Installing $bin $WANT…"
    return 1
}

info "Installing Ollama LLM runtime…"
require curl

if [[ "${CI:-}" == "true" || "${GITHUB_ACTIONS:-}" == "true" ]]; then
    warn "CI mode: skipping Ollama (large download). Install manually: curl -fsSL https://ollama.com/install.sh | sh"
    exit 0
fi

at_version ollama && exit 0

case "$(uname -s)" in
    Linux)
        ARCH="$(uname -m)"
        [[ "$ARCH" == "x86_64" ]]  && URL="https://ollama.com/download/ollama-linux-amd64.tar.zst"
        [[ "$ARCH" == "aarch64" ]] && URL="https://ollama.com/download/ollama-linux-arm64.tar.zst"
        [[ -z "${URL:-}" ]] && die "Unsupported arch: $ARCH"
        mkdir -p "$HOME/.local/bin"
        require zstd || { sudo apt-get install -y zstd 2>/dev/null || sudo dnf install -y zstd 2>/dev/null; }
        info "Downloading Ollama (~800 MB)…"
        curl -fsSL "$URL" -o /tmp/ollama.tar.zst
        tar -I zstd -xf /tmp/ollama.tar.zst -C /tmp
        mv /tmp/bin/ollama "$HOME/.local/bin/ollama"
        chmod +x "$HOME/.local/bin/ollama"
        rm -rf /tmp/ollama.tar.zst /tmp/bin
        ;;
    Darwin)
        if has brew; then brew install ollama
        else die "Install Ollama for macOS from https://ollama.com/download"; fi
        ;;
    *) die "Unsupported OS." ;;
esac

has ollama && info "Ollama $(ollama --version 2>/dev/null | head -1) installed." \
          || die "Ollama binary not found after install."
info "Start Ollama with: ollama serve"
info "Pull a model:      ollama pull llama3.2"
