name: 'Oracle Cloud (OCI) Instance Manager'
description: 'Launch and terminate OCI Compute instances for Packer image testing'

inputs:
  action:
    description: 'Action to perform (launch, terminate)'
    required: true
  image-id:
    description: 'OCI image OCID'
    required: false
  instance-id:
    description: 'Instance OCID to terminate'
    required: false
  region:
    description: 'OCI region'
    required: false
    default: 'us-ashburn-1'
  instance-type:
    description: 'OCI shape'
    required: false
    default: 'VM.Standard.E4.Flex'
  compartment-id:
    description: 'OCI compartment OCID'
    required: true
  subnet-id:
    description: 'OCI subnet OCID'
    required: true
  availability-domain:
    description: 'OCI availability domain'
    required: false

outputs:
  instance-id:
    description: 'Instance OCID'
    value: ${{ steps.launch.outputs.instance_id }}
  public-ip:
    description: 'Public IP address'
    value: ${{ steps.launch.outputs.public_ip }}
  ssh-key-path:
    description: 'Path to SSH private key'
    value: ${{ steps.launch.outputs.ssh_key_path }}
  ssh-user:
    description: 'SSH username'
    value: 'opc'

runs:
  using: 'composite'
  steps:
    - name: Setup OCI CLI
      if: inputs.action == 'launch' || inputs.action == 'terminate'
      shell: bash
      run: |
        # Install OCI CLI if not present
        if ! command -v oci &>/dev/null; then
          echo "Installing OCI CLI..."
          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          export PATH="$HOME/bin:$PATH"
        fi

        # Configure OCI CLI
        mkdir -p ~/.oci
        cat > ~/.oci/config << EOF
        [DEFAULT]
        user=${OCI_USER_OCID}
        fingerprint=${OCI_FINGERPRINT}
        tenancy=${OCI_TENANCY_OCID}
        region=${{ inputs.region }}
        key_file=~/.oci/oci_api_key.pem
        EOF

        chmod 600 ~/.oci/config

    - name: Launch OCI Instance
      if: inputs.action == 'launch'
      id: launch
      shell: bash
      run: |
        echo "Launching OCI instance from image: ${{ inputs.image-id }}"

        INSTANCE_NAME="sindri-test-$(date +%s)"

        # Get availability domain if not specified
        AD="${{ inputs.availability-domain }}"
        if [[ -z "$AD" ]]; then
          AD=$(oci iam availability-domain list \
            --compartment-id ${{ inputs.compartment-id }} \
            --query 'data[0].name' \
            --raw-output)
        fi

        # Generate SSH key for this instance
        ssh-keygen -t rsa -b 4096 -f /tmp/ssh_key_oci -N "" -q
        SSH_PUBLIC_KEY=$(cat /tmp/ssh_key_oci.pub)

        # Create instance
        INSTANCE_JSON=$(oci compute instance launch \
          --compartment-id ${{ inputs.compartment-id }} \
          --availability-domain "$AD" \
          --shape ${{ inputs.instance-type }} \
          --shape-config '{"ocpus": 2, "memoryInGBs": 16}' \
          --image-id ${{ inputs.image-id }} \
          --subnet-id ${{ inputs.subnet-id }} \
          --display-name "$INSTANCE_NAME" \
          --assign-public-ip true \
          --ssh-authorized-keys-file /tmp/ssh_key_oci.pub \
          --freeform-tags '{"Purpose": "packer-test", "AutoTerminate": "true"}' \
          --wait-for-state RUNNING \
          --query 'data')

        INSTANCE_OCID=$(echo "$INSTANCE_JSON" | jq -r '.id')

        echo "Instance OCID: $INSTANCE_OCID"
        echo "instance_id=$INSTANCE_OCID" >> $GITHUB_OUTPUT

        # Get VNIC attachments to find public IP
        sleep 30  # Wait for VNIC to be ready

        VNIC_ID=$(oci compute vnic-attachment list \
          --compartment-id ${{ inputs.compartment-id }} \
          --instance-id "$INSTANCE_OCID" \
          --query 'data[0]."vnic-id"' \
          --raw-output)

        PUBLIC_IP=$(oci network vnic get \
          --vnic-id "$VNIC_ID" \
          --query 'data."public-ip"' \
          --raw-output)

        echo "Public IP: $PUBLIC_IP"
        echo "public_ip=$PUBLIC_IP" >> $GITHUB_OUTPUT
        echo "ssh_key_path=/tmp/ssh_key_oci" >> $GITHUB_OUTPUT

        chmod 600 /tmp/ssh_key_oci

        # Wait for SSH
        echo "Waiting for SSH to be ready..."
        for i in {1..30}; do
          if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i /tmp/ssh_key_oci opc@$PUBLIC_IP "echo SSH ready" 2>/dev/null; then
            echo "SSH is ready"
            break
          fi
          echo "Waiting for SSH... ($i/30)"
          sleep 10
        done

    - name: Terminate OCI Instance
      if: inputs.action == 'terminate'
      shell: bash
      run: |
        INSTANCE_OCID="${{ inputs.instance-id }}"

        if [[ -n "$INSTANCE_OCID" && "$INSTANCE_OCID" != "null" ]]; then
          echo "Terminating OCI instance: $INSTANCE_OCID"

          oci compute instance terminate \
            --instance-id "$INSTANCE_OCID" \
            --preserve-boot-volume false \
            --force \
            --wait-for-state TERMINATED || true

          echo "Instance terminated"
        else
          echo "No instance OCID provided, skipping termination"
        fi

        # Cleanup SSH key
        rm -f /tmp/ssh_key_oci /tmp/ssh_key_oci.pub 2>/dev/null || true
