name: Deploy Provider
description: Deploy Sindri to any supported provider (unified deployment action)

inputs:
  provider:
    description: Provider to deploy to (docker, fly, devpod-aws, devpod-gcp, devpod-azure, devpod-do, devpod-k8s)
    required: true
  image:
    description: Docker image to use
    required: false
    default: "sindri:latest"
  image-artifact:
    description: Name of image artifact to download
    required: false
    default: ""
  config-path:
    description: Path to sindri.yaml configuration
    required: false
    default: ""
  extension-profile:
    description: Extension profile to deploy with (determines resource requirements)
    required: false
    default: "minimal"
  test-level:
    description: Test level being run (affects resource allocation)
    required: false
    default: "profile"

outputs:
  target-id:
    description: Target identifier (container name, app name, or workspace ID)
    value: ${{ steps.deploy.outputs.target-id }}

runs:
  using: composite
  steps:
    - name: Determine config path
      id: config
      shell: bash
      run: |
        if [[ -n "${{ inputs.config-path }}" ]]; then
          CONFIG="${{ inputs.config-path }}"
        else
          # For extension-level tests, use fullstack config for more resources
          # This ensures we have enough headroom for heavy extensions (guacamole, xfce, etc.)
          if [[ "${{ inputs.test-level }}" == "extension" ]]; then
            PROFILE="fullstack"
            echo "::notice::Using fullstack config for extension-level tests (ensures sufficient resources)"
          else
            PROFILE="${{ inputs.extension-profile }}"
          fi

          # Map provider + profile to example config
          case "${{ inputs.provider }}" in
            docker)
              CONFIG="examples/docker/${PROFILE}.sindri.yaml"
              ;;
            fly)
              CONFIG="examples/fly/${PROFILE}.sindri.yaml"
              ;;
            devpod-aws)
              CONFIG="examples/devpod/aws/${PROFILE}.sindri.yaml"
              ;;
            devpod-gcp)
              CONFIG="examples/devpod/gcp/${PROFILE}.sindri.yaml"
              ;;
            devpod-azure)
              CONFIG="examples/devpod/azure/${PROFILE}.sindri.yaml"
              ;;
            devpod-do)
              CONFIG="examples/devpod/digitalocean/${PROFILE}.sindri.yaml"
              ;;
            devpod-k8s|kubernetes)
              CONFIG="examples/devpod/kubernetes/${PROFILE}.sindri.yaml"
              ;;
            *)
              echo "::error::Unknown provider: ${{ inputs.provider }}"
              exit 1
              ;;
          esac

          # Fallback to minimal if profile-specific config doesn't exist
          if [[ ! -f "$CONFIG" ]]; then
            echo "::warning::Profile config $CONFIG not found, falling back to minimal"
            case "${{ inputs.provider }}" in
              docker) CONFIG="examples/docker/minimal.sindri.yaml" ;;
              fly) CONFIG="examples/fly/minimal.sindri.yaml" ;;
              devpod-aws) CONFIG="examples/devpod/aws/minimal.sindri.yaml" ;;
              devpod-gcp) CONFIG="examples/devpod/gcp/minimal.sindri.yaml" ;;
              devpod-azure) CONFIG="examples/devpod/azure/minimal.sindri.yaml" ;;
              devpod-do) CONFIG="examples/devpod/digitalocean/minimal.sindri.yaml" ;;
              devpod-k8s|kubernetes) CONFIG="examples/devpod/kubernetes/minimal.sindri.yaml" ;;
            esac
          fi
        fi

        echo "config=$CONFIG" >> $GITHUB_OUTPUT
        echo "::notice title=Config::Using $CONFIG (test-level: ${{ inputs.test-level }}, profile: ${{ inputs.extension-profile }})"

    - name: Download image artifact (if specified)
      if: inputs.image-artifact != ''
      uses: actions/download-artifact@v6
      with:
        name: ${{ inputs.image-artifact }}

    - name: Load Docker image from artifact
      if: inputs.image-artifact != ''
      shell: bash
      run: |
        if [[ -f "sindri-image.tar.gz" ]]; then
          echo "Loading Docker image from artifact..."
          gunzip -c sindri-image.tar.gz | docker load
          echo "✓ Image loaded: ${{ inputs.image }}"
        fi

    - name: Deploy
      id: deploy
      shell: bash
      run: |
        PROVIDER="${{ inputs.provider }}"
        RUN_ID="${{ github.run_id }}"
        RUN_NUMBER="${{ github.run_number }}"
        CONFIG="${{ steps.config.outputs.config }}"

        echo "Deploying to $PROVIDER..."

        case "$PROVIDER" in
          docker)
            # Get container name from config (needed for pre-cleanup)
            TARGET_ID=$(yq '.name' "$CONFIG" 2>/dev/null || echo "sindri-test")

            # PRE-CLEANUP: Remove stale resources from previous runs
            echo "Pre-cleanup: Ensuring clean slate for Docker"
            docker rm -f "$TARGET_ID" 2>/dev/null || true
            docker volume ls -q --filter "name=${TARGET_ID}_home" | xargs -r docker volume rm 2>/dev/null || true
            if [[ -f docker-compose.yml ]]; then
              docker compose -f docker-compose.yml down -v 2>/dev/null || true
            fi

            # Deploy using pre-built image (skip build if image already exists)
            if docker image inspect "${{ inputs.image }}" >/dev/null 2>&1; then
              echo "Using pre-built image: ${{ inputs.image }}"
              IMAGE="${{ inputs.image }}" ./cli/sindri deploy --provider docker --config "$CONFIG"
            else
              echo "Pre-built image not found, building from Dockerfile"
              ./cli/sindri deploy --provider docker --config "$CONFIG"
            fi

            # Fix permissions on volume
            docker exec --user root "$TARGET_ID" chown -R developer:developer /alt/home/developer 2>/dev/null || true

            # Verify container is ready
            docker exec "$TARGET_ID" bash -c 'echo "Container ready"'

            echo "✓ Deployed to Docker: $TARGET_ID"
            ;;

          fly)
            APP_NAME="sindri-ci-${RUN_ID}-${RUN_NUMBER}"

            # Deploy using fly adapter (CI mode, config as positional arg)
            ./deploy/adapters/fly-adapter.sh deploy --ci-mode "$CONFIG"

            TARGET_ID="$APP_NAME"
            echo "✓ Deployed to Fly.io: $TARGET_ID"
            ;;

          devpod-*)
            BACKEND="${PROVIDER#devpod-}"
            WORKSPACE_ID="sindri-${RUN_ID}"

            # Deploy using devpod adapter (config as positional arg)
            ./deploy/adapters/devpod-adapter.sh deploy "$CONFIG"

            TARGET_ID="$WORKSPACE_ID"
            echo "✓ Deployed to DevPod ($BACKEND): $TARGET_ID"
            ;;

          *)
            echo "::error::Unsupported provider: $PROVIDER"
            exit 1
            ;;
        esac

        echo "target-id=$TARGET_ID" >> $GITHUB_OUTPUT
        echo "::notice title=Deployed::Target ID: $TARGET_ID"
