name: Deploy Provider
description: Deploy Sindri to any supported provider (unified deployment action)

inputs:
  provider:
    description: Provider to deploy to (docker, fly, devpod-aws, devpod-gcp, devpod-azure, devpod-do, devpod-k8s)
    required: true
  image:
    description: Docker image to use
    required: false
    default: "sindri:latest"
  image-artifact:
    description: Name of image artifact to download
    required: false
    default: ""
  config-path:
    description: Path to sindri.yaml configuration
    required: false
    default: ""
  extension-profile:
    description: Extension profile to deploy with (determines resource requirements)
    required: false
    default: "minimal"
  test-level:
    description: Test level being run (affects resource allocation)
    required: false
    default: "profile"

outputs:
  target-id:
    description: Target identifier (container name, app name, or workspace ID)
    value: ${{ steps.deploy.outputs.target-id }}

runs:
  using: composite
  steps:
    - name: Determine config path
      id: config
      shell: bash
      run: |
        if [[ -n "${{ inputs.config-path }}" ]]; then
          CONFIG="${{ inputs.config-path }}"
        else
          # For extension-level tests, use fullstack config for more resources
          # This ensures we have enough headroom for heavy extensions (guacamole, xfce, etc.)
          if [[ "${{ inputs.test-level }}" == "extension" ]]; then
            PROFILE="fullstack"
            echo "::notice::Using fullstack config for extension-level tests (ensures sufficient resources)"
          else
            PROFILE="${{ inputs.extension-profile }}"
          fi

          # Map provider + profile to example config
          case "${{ inputs.provider }}" in
            docker)
              CONFIG="examples/docker/${PROFILE}.sindri.yaml"
              ;;
            fly)
              CONFIG="examples/fly/${PROFILE}.sindri.yaml"
              ;;
            devpod-aws)
              CONFIG="examples/devpod/aws/${PROFILE}.sindri.yaml"
              ;;
            devpod-gcp)
              CONFIG="examples/devpod/gcp/${PROFILE}.sindri.yaml"
              ;;
            devpod-azure)
              CONFIG="examples/devpod/azure/${PROFILE}.sindri.yaml"
              ;;
            devpod-do)
              CONFIG="examples/devpod/digitalocean/${PROFILE}.sindri.yaml"
              ;;
            devpod-k8s|kubernetes)
              CONFIG="examples/devpod/kubernetes/${PROFILE}.sindri.yaml"
              ;;
            *)
              echo "::error::Unknown provider: ${{ inputs.provider }}"
              exit 1
              ;;
          esac

          # Fallback to minimal if profile-specific config doesn't exist
          if [[ ! -f "$CONFIG" ]]; then
            echo "::warning::Profile config $CONFIG not found, falling back to minimal"
            case "${{ inputs.provider }}" in
              docker) CONFIG="examples/docker/minimal.sindri.yaml" ;;
              fly) CONFIG="examples/fly/minimal.sindri.yaml" ;;
              devpod-aws) CONFIG="examples/devpod/aws/minimal.sindri.yaml" ;;
              devpod-gcp) CONFIG="examples/devpod/gcp/minimal.sindri.yaml" ;;
              devpod-azure) CONFIG="examples/devpod/azure/minimal.sindri.yaml" ;;
              devpod-do) CONFIG="examples/devpod/digitalocean/minimal.sindri.yaml" ;;
              devpod-k8s|kubernetes) CONFIG="examples/devpod/kubernetes/minimal.sindri.yaml" ;;
            esac
          fi
        fi

        echo "config=$CONFIG" >> $GITHUB_OUTPUT
        echo "::notice title=Config::Using $CONFIG (test-level: ${{ inputs.test-level }}, profile: ${{ inputs.extension-profile }})"

    - name: Download image artifact (if specified)
      if: inputs.image-artifact != ''
      uses: actions/download-artifact@v6
      with:
        name: ${{ inputs.image-artifact }}

    - name: Load Docker image from artifact
      if: inputs.image-artifact != ''
      shell: bash
      run: |
        if [[ -f "sindri-image.tar.gz" ]]; then
          echo "Loading Docker image from artifact..."
          gunzip -c sindri-image.tar.gz | docker load
          echo "✓ Image loaded: ${{ inputs.image }}"
        fi

    - name: Install flyctl CLI
      if: inputs.provider == 'fly'
      shell: bash
      run: |
        echo "Installing flyctl CLI..."
        curl -L https://fly.io/install.sh | sh
        echo "$HOME/.fly/bin" >> $GITHUB_PATH
        export PATH="$HOME/.fly/bin:$PATH"
        flyctl version
        echo "✓ flyctl installed"

    - name: Setup kind cluster for devpod-k8s
      if: inputs.provider == 'devpod-k8s'
      shell: bash
      run: |
        echo "Setting up kind cluster for kubernetes testing..."

        # Install kind if not present
        if ! command -v kind &>/dev/null; then
          echo "Installing kind..."
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
        fi

        # Create kind cluster
        echo "Creating kind cluster: sindri-ci"
        kind create cluster --name sindri-ci --wait 60s

        # Load the image into kind
        echo "Loading image into kind cluster..."
        kind load docker-image "${{ inputs.image }}" --name sindri-ci

        # Also tag and load as sindri:latest
        docker tag "${{ inputs.image }}" sindri:latest
        kind load docker-image sindri:latest --name sindri-ci

        echo "✓ Kind cluster ready with image loaded"

    - name: Install DevPod CLI
      if: startsWith(inputs.provider, 'devpod-')
      shell: bash
      run: |
        echo "Installing DevPod CLI..."
        curl -L -o devpod "https://github.com/loft-sh/devpod/releases/latest/download/devpod-linux-amd64"
        chmod +x devpod
        sudo mv devpod /usr/local/bin/devpod
        devpod version
        echo "✓ DevPod installed"

    - name: Deploy
      id: deploy
      shell: bash
      run: |
        PROVIDER="${{ inputs.provider }}"
        RUN_ID="${{ github.run_id }}"
        RUN_NUMBER="${{ github.run_number }}"
        CONFIG="${{ steps.config.outputs.config }}"

        echo "Deploying to $PROVIDER..."

        case "$PROVIDER" in
          docker)
            # Get container name from config (needed for pre-cleanup)
            TARGET_ID=$(yq '.name' "$CONFIG" 2>/dev/null || echo "sindri-test")

            # PRE-CLEANUP: Remove stale resources from previous runs
            echo "Pre-cleanup: Ensuring clean slate for Docker"
            docker rm -f "$TARGET_ID" 2>/dev/null || true
            docker volume ls -q --filter "name=${TARGET_ID}_home" | xargs -r docker volume rm 2>/dev/null || true
            if [[ -f docker-compose.yml ]]; then
              docker compose -f docker-compose.yml down -v 2>/dev/null || true
            fi

            # Tag pre-built image as sindri:latest (what docker-adapter expects)
            if docker image inspect "${{ inputs.image }}" >/dev/null 2>&1; then
              echo "Tagging pre-built image as sindri:latest"
              docker tag "${{ inputs.image }}" sindri:latest
            fi

            # Deploy using docker-adapter with --ci-mode (forces autoInstall=false for clean tests)
            ./deploy/adapters/docker-adapter.sh deploy --skip-build --ci-mode "$CONFIG"

            # Fix permissions on volume
            docker exec --user root "$TARGET_ID" chown -R developer:developer /alt/home/developer 2>/dev/null || true

            # Verify container is ready
            docker exec "$TARGET_ID" bash -c 'echo "Container ready"'

            echo "✓ Deployed to Docker: $TARGET_ID"
            ;;

          fly)
            APP_NAME="sindri-ci-${RUN_ID}-${RUN_NUMBER}"

            # Deploy using fly adapter (CI mode, config as positional arg)
            ./deploy/adapters/fly-adapter.sh deploy --ci-mode "$CONFIG"

            TARGET_ID="$APP_NAME"
            echo "✓ Deployed to Fly.io: $TARGET_ID"
            ;;

          devpod-*)
            BACKEND="${PROVIDER#devpod-}"
            WORKSPACE_ID="sindri-${RUN_ID}"

            # Build extra flags for specific providers
            EXTRA_FLAGS=""
            if [[ "$PROVIDER" == "devpod-k8s" ]]; then
              # For k8s, we already loaded the image into kind cluster in setup step
              EXTRA_FLAGS="--skip-build"
            fi

            # Deploy using devpod adapter with --ci-mode (forces autoInstall=false)
            ./deploy/adapters/devpod-adapter.sh deploy --ci-mode $EXTRA_FLAGS "$CONFIG"

            TARGET_ID="$WORKSPACE_ID"
            echo "✓ Deployed to DevPod ($BACKEND): $TARGET_ID"
            ;;

          *)
            echo "::error::Unsupported provider: $PROVIDER"
            exit 1
            ;;
        esac

        echo "target-id=$TARGET_ID" >> $GITHUB_OUTPUT
        echo "::notice title=Deployed::Target ID: $TARGET_ID"
