#!/usr/bin/env bash
# Shannon — signal processing playground — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing Shannon (signal processing playground)…"
require python3

for pkg in numpy scipy matplotlib jupyter; do
    python3 -m pip install --user "$pkg" 2>/dev/null \
        || warn "Could not install $pkg — some Shannon features may be unavailable."
done

SHANNON_DIR="$HOME/.local/share/sindri/shannon"
require git
if [[ -d "$SHANNON_DIR" ]]; then
    git -C "$SHANNON_DIR" pull --ff-only 2>/dev/null || true
else
    git clone --depth 1 https://github.com/sindri-dev/shannon "$SHANNON_DIR" 2>/dev/null \
        || warn "Could not clone shannon. Install dependencies only."
fi

info "Shannon signal processing playground ready."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
