#!/usr/bin/env bash
# openfang — offensive-sec learning harness — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing openfang offensive-security learning harness…"
require python3

OPENFANG_DIR="$HOME/.local/share/sindri/openfang"
require git

if [[ -d "$OPENFANG_DIR" ]]; then
    info "Updating openfang…"
    git -C "$OPENFANG_DIR" pull --ff-only 2>/dev/null || true
else
    git clone --depth 1 https://github.com/sindri-dev/openfang "$OPENFANG_DIR" 2>/dev/null \
        || die "Failed to clone openfang."
fi

# Install Python deps if requirements.txt exists
if [[ -f "$OPENFANG_DIR/requirements.txt" ]]; then
    python3 -m pip install --user -r "$OPENFANG_DIR/requirements.txt" 2>/dev/null || true
fi

info "openfang installed at $OPENFANG_DIR"
warn "For security-training purposes only. Use only on systems you own or have permission to test."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
