#!/usr/bin/env bash
# Prometheus/Grafana local observability stack — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing local monitoring stack (Prometheus + Grafana via Docker)…"
require docker

MONITORING_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/sindri/monitoring"
mkdir -p "$MONITORING_DIR"/{prometheus,grafana}

# Write a minimal Prometheus config if absent
if [[ ! -f "$MONITORING_DIR/prometheus/prometheus.yml" ]]; then
    cat > "$MONITORING_DIR/prometheus/prometheus.yml" <<'EOF'
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
EOF
    info "Created minimal prometheus.yml."
fi

# Simple docker-compose-style launch function (no compose dependency)
if docker ps --format '{{.Names}}' 2>/dev/null | grep -q "sindri-prometheus"; then
    warn "sindri-prometheus container already running. Skipping."
else
    info "Starting Prometheus container…"
    docker run -d --name sindri-prometheus --restart unless-stopped \
        -p 9090:9090 \
        -v "$MONITORING_DIR/prometheus:/etc/prometheus:ro" \
        prom/prometheus:latest \
        || warn "Failed to start Prometheus — Docker may not be running."
fi

if docker ps --format '{{.Names}}' 2>/dev/null | grep -q "sindri-grafana"; then
    warn "sindri-grafana container already running. Skipping."
else
    info "Starting Grafana container…"
    docker run -d --name sindri-grafana --restart unless-stopped \
        -p 3001:3000 \
        -v "$MONITORING_DIR/grafana:/var/lib/grafana" \
        grafana/grafana:latest \
        || warn "Failed to start Grafana — Docker may not be running."
fi

info "Prometheus: http://localhost:9090"
info "Grafana:    http://localhost:3001  (admin/admin)"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
