#!/usr/bin/env bash
# Prometheus/Grafana local observability stack — install
# Generated by tools/generate_scripts.py
set -euo pipefail

# ── helpers ───────────────────────────────────────────────────────────────────
_g="\033[0;32m" _y="\033[0;33m" _r="\033[0;31m" _b="\033[0m"
info()    { echo -e "${_g}[sindri]${_b} $*"; }
warn()    { echo -e "${_y}[warn]${_b}  $*"; }
die()     { echo -e "${_r}[error]${_b} $*" >&2; exit 1; }
has()     { command -v "$1" &>/dev/null; }
require() { has "$1" || die "Required: $1 — install it before running this script."; }

# ── version contract (ADR-024) ─────────────────────────────────────────────────
# SINDRI_COMPONENT_VERSION: injected by the sindri CLI before invoking this script.
# Carries the exact version declared in registry component.yaml.
# Scripts MUST exit 0 without side effects when already at target version.
WANT="${SINDRI_COMPONENT_VERSION:-1.0.0}"

# Extract semver from binary's version output
version_of() {
    "${1}" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || "${1}" version  2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || echo ""
}

# Return 0 (true) and print status if $1 binary is already at $WANT.
# Return 1 (false) and print upgrade/install intent otherwise.
at_version() {
    local bin="$1" have
    have=$(version_of "$bin")
    if [[ -n "$WANT" && ( "$have" == "$WANT"* || "$have" == *"$WANT"* ) ]]; then
        info "$bin $WANT already installed. Nothing to do."
        return 0
    fi
    [[ -n "$have" ]] && info "$bin: $have → $WANT" || info "Installing $bin $WANT…"
    return 1
}

info "Installing local monitoring stack (Prometheus + Grafana via Docker)…"
require docker

MONITORING_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/sindri/monitoring"
mkdir -p "$MONITORING_DIR"/{prometheus,grafana}

# Write a minimal Prometheus config if absent
if [[ ! -f "$MONITORING_DIR/prometheus/prometheus.yml" ]]; then
    cat > "$MONITORING_DIR/prometheus/prometheus.yml" <<'EOF'
global:
  scrape_interval: 15s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
EOF
    info "Created minimal prometheus.yml."
fi

# Simple docker-compose-style launch function (no compose dependency)
if docker ps --format '{{.Names}}' 2>/dev/null | grep -q "sindri-prometheus"; then
    warn "sindri-prometheus container already running. Skipping."
else
    info "Starting Prometheus container…"
    docker run -d --name sindri-prometheus --restart unless-stopped \
        -p 9090:9090 \
        -v "$MONITORING_DIR/prometheus:/etc/prometheus:ro" \
        prom/prometheus:latest \
        || warn "Failed to start Prometheus — Docker may not be running."
fi

if docker ps --format '{{.Names}}' 2>/dev/null | grep -q "sindri-grafana"; then
    warn "sindri-grafana container already running. Skipping."
else
    info "Starting Grafana container…"
    docker run -d --name sindri-grafana --restart unless-stopped \
        -p 3001:3000 \
        -v "$MONITORING_DIR/grafana:/var/lib/grafana" \
        grafana/grafana:latest \
        || warn "Failed to start Grafana — Docker may not be running."
fi

info "Prometheus: http://localhost:9090"
info "Grafana:    http://localhost:3001  (admin/admin)"
