#!/usr/bin/env bash
# Prometheus/Grafana local observability stack — uninstall
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Uninstalling monitoring stack (Docker containers)…"
docker stop sindri-prometheus sindri-grafana 2>/dev/null || true
docker rm   sindri-prometheus sindri-grafana 2>/dev/null || true
read -rp "Remove monitoring data ($HOME/.local/share/sindri/monitoring)? [y/N] " ans
[[ "$ans" =~ ^[Yy]$ ]] && rm -rf "$HOME/.local/share/sindri/monitoring" || info "Data retained."
info "Monitoring stack removed."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
