#!/usr/bin/env bash
# Clarity spec generator CLI — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing Clarity spec generator CLI…"
require python3

if has uv; then
    uv tool install clarity-cli 2>/dev/null || true
elif has pip3; then
    pip3 install --user clarity-cli 2>/dev/null || true
fi

if ! has clarity; then
    require git
    CLARITY_DIR="$HOME/.local/share/sindri/clarity"
    if [[ -d "$CLARITY_DIR" ]]; then
        git -C "$CLARITY_DIR" pull --ff-only 2>/dev/null || true
    else
        git clone --depth 1 https://github.com/sindri-dev/clarity "$CLARITY_DIR" 2>/dev/null \
            || warn "Could not clone clarity. Install manually."
    fi
fi

info "Clarity spec generator ready."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
