name: 'GCP Instance Manager'
description: 'Launch and terminate GCP Compute Engine instances for Packer image testing'

inputs:
  action:
    description: 'Action to perform (launch, terminate)'
    required: true
  image-id:
    description: 'GCP image name'
    required: false
  instance-id:
    description: 'Instance name to terminate'
    required: false
  region:
    description: 'GCP zone'
    required: false
    default: 'us-central1-a'
  instance-type:
    description: 'Machine type'
    required: false
    default: 'e2-medium'
  project-id:
    description: 'GCP project ID'
    required: false

outputs:
  instance-id:
    description: 'Instance name'
    value: ${{ steps.launch.outputs.instance_id }}
  public-ip:
    description: 'External IP address'
    value: ${{ steps.launch.outputs.public_ip }}
  ssh-key-path:
    description: 'Path to SSH private key'
    value: ${{ steps.launch.outputs.ssh_key_path }}
  ssh-user:
    description: 'SSH username'
    value: ${{ steps.launch.outputs.ssh_user }}

runs:
  using: 'composite'
  steps:
    - name: Launch GCP Instance
      if: inputs.action == 'launch'
      id: launch
      shell: bash
      run: |
        echo "Launching GCP instance from image: ${{ inputs.image-id }}"

        INSTANCE_NAME="sindri-test-$(date +%s)"
        ZONE="${{ inputs.region }}"
        PROJECT="${{ inputs.project-id }}"
        SSH_USER="sindri"
        SSH_KEY_PATH="/tmp/ssh_key_gcp"

        # Set project if provided
        if [[ -n "$PROJECT" ]]; then
          gcloud config set project "$PROJECT"
        fi

        # Generate SSH key pair for this instance
        ssh-keygen -t ed25519 -f "$SSH_KEY_PATH" -N "" -C "$SSH_USER"
        chmod 600 "$SSH_KEY_PATH"

        # Format SSH public key for GCP metadata
        # Format: username:ssh-ed25519 AAAA... username
        SSH_PUB_KEY=$(cat "${SSH_KEY_PATH}.pub")
        GCP_SSH_KEY="${SSH_USER}:${SSH_PUB_KEY}"

        # Create instance with SSH key in metadata (not OS Login)
        # OS Login and direct SSH key auth are different patterns - we use direct key injection
        # for compatibility with external SSH tools like InSpec
        gcloud compute instances create "$INSTANCE_NAME" \
          --zone="$ZONE" \
          --machine-type=${{ inputs.instance-type }} \
          --image=${{ inputs.image-id }} \
          --tags=packer-test,auto-terminate \
          --metadata="ssh-keys=${GCP_SSH_KEY}" \
          --format=json > /tmp/gcp-instance-info.json

        EXTERNAL_IP=$(jq -r '.[0].networkInterfaces[0].accessConfigs[0].natIP' /tmp/gcp-instance-info.json)

        echo "Instance Name: $INSTANCE_NAME"
        echo "External IP: $EXTERNAL_IP"
        echo "SSH User: $SSH_USER"

        echo "instance_id=$INSTANCE_NAME" >> $GITHUB_OUTPUT
        echo "public_ip=$EXTERNAL_IP" >> $GITHUB_OUTPUT
        echo "ssh_key_path=$SSH_KEY_PATH" >> $GITHUB_OUTPUT
        echo "ssh_user=$SSH_USER" >> $GITHUB_OUTPUT

        # Wait for SSH using direct SSH connection (not gcloud compute ssh)
        echo "Waiting for SSH to be ready..."
        for i in {1..30}; do
          if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 -i "$SSH_KEY_PATH" "${SSH_USER}@${EXTERNAL_IP}" "echo SSH ready" 2>/dev/null; then
            echo "SSH is ready"
            break
          fi
          echo "Waiting for SSH... ($i/30)"
          sleep 10
        done

    - name: Terminate GCP Instance
      if: inputs.action == 'terminate'
      shell: bash
      run: |
        INSTANCE_NAME="${{ inputs.instance-id }}"
        ZONE="${{ inputs.region }}"
        PROJECT="${{ inputs.project-id }}"

        if [[ -n "$PROJECT" ]]; then
          gcloud config set project "$PROJECT"
        fi

        if [[ -n "$INSTANCE_NAME" && "$INSTANCE_NAME" != "null" ]]; then
          echo "Terminating GCP instance: $INSTANCE_NAME"

          gcloud compute instances delete "$INSTANCE_NAME" \
            --zone="$ZONE" \
            --quiet

          echo "Instance deleted"
        else
          echo "No instance name provided, skipping termination"
        fi

        # Cleanup SSH key
        rm -f /tmp/ssh_key_gcp /tmp/ssh_key_gcp.pub 2>/dev/null || true
