#!/usr/bin/env bash
# GitHub CLI install via distro script (alias of binary:gh) — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Configuring GitHub CLI…"
require gh

if gh auth status &>/dev/null; then
    warn "GitHub CLI already authenticated."
else
    info "Authenticating with GitHub (browser flow)…"
    gh auth login --web --git-protocol https \
        || warn "Authentication skipped. Run 'gh auth login' to authenticate."
fi

info "gh $(gh --version 2>/dev/null | head -1) ready."
info "Common commands: gh repo clone, gh pr create, gh issue list"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
