#!/usr/bin/env bash
# GitHub CLI install via distro script (alias of binary:gh) — uninstall
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Uninstalling github-cli…"
if [ -e "$HOME/.local/bin/github-cli" ]; then
    rm -f "$HOME/.local/bin/github-cli"
    info "github-cli binary removed from ~/.local/bin/github-cli."
    warn "Configuration files and data were NOT removed."
else
    info "github-cli not present at ~/.local/bin/github-cli; nothing to remove."
    sindri::emit phase-complete '"change":false'
    exit 0
fi

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
