#!/usr/bin/env bash
# GitHub CLI install via distro script (alias of binary:gh) — validate
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Validating GitHub CLI…"
require gh
gh --version | head -1 || die "gh not responding."
gh auth status &>/dev/null || warn "Not authenticated. Run: gh auth login"
info "gh OK: $(gh --version 2>/dev/null | head -1)"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
