#!/usr/bin/env bash
# Ralph — personal coding agent — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing Ralph — personal coding agent…"
require claude
require node

# Ensure Claude Code is configured
if ! claude --version &>/dev/null; then
    die "Claude Code is required. Install with: npm install -g @anthropic-ai/claude-code"
fi

# Ralph is a configuration layer on top of Claude Code
RALPH_DIR="$HOME/.config/sindri/ralph"
mkdir -p "$RALPH_DIR"

cat > "$RALPH_DIR/config.yaml" <<'EOF'
# Ralph configuration
agent: ralph
model: claude-opus-4-7
tools:
  - bash
  - read
  - write
  - edit
memory: persistent
auto_compact: true
EOF

info "Ralph configured at $RALPH_DIR/config.yaml"
info "Start a Ralph session: claude --config $RALPH_DIR/config.yaml"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
