#!/bin/bash
set -euo pipefail

# configure-agent.sh
# Reads console endpoint from environment variables (set via sindri.yaml) and
# writes the sindri-agent configuration file.

CONFIG_DIR="${HOME}/.config/sindri-agent"
CONFIG_FILE="${CONFIG_DIR}/config.yaml"
LOG_FILE="/tmp/sindri-agent.log"

print_status "Configuring sindri-agent..."

# Ensure config directory exists
mkdir -p "${CONFIG_DIR}"

# Resolve console URL from environment, falling back to sindri.yaml if available
CONSOLE_URL="${SINDRI_CONSOLE_URL:-}"
CONSOLE_API_KEY="${SINDRI_CONSOLE_API_KEY:-}"
HEARTBEAT_INTERVAL="${SINDRI_AGENT_HEARTBEAT:-30}"
METRICS_INTERVAL="${SINDRI_AGENT_METRICS:-60}"

# Attempt to read from sindri.yaml if env vars are not set
if [[ -z "${CONSOLE_URL}" ]]; then
    SINDRI_YAML_PATHS=(
        "${HOME}/sindri.yaml"
        "${HOME}/.sindri.yaml"
        "/workspace/sindri.yaml"
        "/workspaces/sindri.yaml"
    )

    for yaml_path in "${SINDRI_YAML_PATHS[@]}"; do
        if [[ -f "${yaml_path}" ]]; then
            print_status "Reading console endpoint from ${yaml_path}..."
            # Extract console URL using simple grep/sed (no yq dependency required)
            extracted_url=$(grep -E '^\s*console_url\s*:' "${yaml_path}" 2>/dev/null | \
                            sed 's/.*console_url\s*:\s*//' | \
                            tr -d "\"'" | \
                            head -n1 | \
                            xargs 2>/dev/null || true)
            if [[ -n "${extracted_url}" ]]; then
                CONSOLE_URL="${extracted_url}"
                print_status "Found console URL in sindri.yaml: ${CONSOLE_URL}"
                break
            fi
        fi
    done
fi

# Warn if console URL is still not configured
if [[ -z "${CONSOLE_URL}" ]]; then
    print_warning "SINDRI_CONSOLE_URL is not set and could not be read from sindri.yaml"
    print_warning "The agent will start but cannot connect to the Console until configured"
    print_warning "Set SINDRI_CONSOLE_URL in your environment or sindri.yaml and re-run configure-agent.sh"
fi

if [[ -z "${CONSOLE_API_KEY}" ]]; then
    print_warning "SINDRI_CONSOLE_API_KEY is not set"
    print_warning "The agent will be unable to authenticate with the Console"
fi

# Generate an instance ID if not already present
INSTANCE_ID_FILE="${CONFIG_DIR}/instance-id"
if [[ -f "${INSTANCE_ID_FILE}" ]]; then
    INSTANCE_ID=$(cat "${INSTANCE_ID_FILE}")
    print_status "Reusing existing instance ID: ${INSTANCE_ID}"
else
    # Generate deterministic instance ID from hostname + a random suffix
    HOSTNAME_PART=$(hostname -s 2>/dev/null || echo "instance")
    RANDOM_SUFFIX=$(head -c 4 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 8)
    INSTANCE_ID="${HOSTNAME_PART}-${RANDOM_SUFFIX}"
    echo "${INSTANCE_ID}" > "${INSTANCE_ID_FILE}"
    print_status "Generated new instance ID: ${INSTANCE_ID}"
fi

# Write the agent configuration file
cat > "${CONFIG_FILE}" <<EOF
# Sindri Console Agent Configuration
# Generated by configure-agent.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Do not edit manually - re-run configure-agent.sh to regenerate

instance:
  id: "${INSTANCE_ID}"
  hostname: "$(hostname -f 2>/dev/null || hostname -s 2>/dev/null || echo "unknown")"

console:
  url: "${CONSOLE_URL}"
  api_key: "${CONSOLE_API_KEY}"

agent:
  heartbeat_interval: ${HEARTBEAT_INTERVAL}
  metrics_interval: ${METRICS_INTERVAL}
  log_file: "${LOG_FILE}"
  pid_file: "/tmp/sindri-agent.pid"
EOF

chmod 600 "${CONFIG_FILE}"
print_success "Agent configuration written to ${CONFIG_FILE}"
print_status "Instance ID: ${INSTANCE_ID}"

if [[ -n "${CONSOLE_URL}" ]]; then
    print_success "Console endpoint: ${CONSOLE_URL}"
fi
