#!/usr/bin/env bash
# GitHub Spec Kit — spec-driven development — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing GitHub Spec Kit (spec-driven development)…"
require python3

# Install via pip/uv
if has uv; then
    uv tool install spec-kit 2>/dev/null || true
elif has pip3; then
    pip3 install --user spec-kit 2>/dev/null || true
fi

# Fallback: clone from GitHub if not available as package
if ! has spec; then
    require git
    SPEC_DIR="$HOME/.local/share/sindri/spec-kit"
    if [[ -d "$SPEC_DIR" ]]; then
        info "Updating spec-kit…"
        git -C "$SPEC_DIR" pull --ff-only 2>/dev/null || true
    else
        git clone --depth 1 https://github.com/sindri-dev/spec-kit "$SPEC_DIR" 2>/dev/null \
            || warn "Could not clone spec-kit. Install manually."
    fi
    [[ -f "$SPEC_DIR/spec" ]] && { cp "$SPEC_DIR/spec" "$HOME/.local/bin/spec"; chmod +x "$HOME/.local/bin/spec"; }
fi

has spec && info "spec-kit installed: $(spec --version 2>/dev/null || echo ok)" \
         || warn "spec-kit installed but 'spec' not in PATH. Add ~/.local/bin to PATH."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
