#!/usr/bin/env bash
# .NET SDK via Microsoft install script — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing .NET SDK via Microsoft install script…"
require curl

CHANNEL="${DOTNET_CHANNEL:-LTS}"
INSTALL_DIR="${DOTNET_INSTALL_DIR:-$HOME/.dotnet}"
export DOTNET_ROOT="$INSTALL_DIR"
export PATH="$INSTALL_DIR:$PATH"

at_version dotnet && exit 0

info "Fetching dotnet-install.sh (channel: $CHANNEL)…"
curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin \
    --channel "$CHANNEL" \
    --install-dir "$INSTALL_DIR" \
    --no-path \
    || die ".NET install failed."

# Persist to shell rc
for rc in ~/.bashrc ~/.zshrc; do
    [[ -f "$rc" ]] && grep -q "DOTNET_ROOT" "$rc" && continue
    [[ -f "$rc" ]] && cat >> "$rc" <<'RCEOF'

# .NET SDK
export DOTNET_ROOT="$HOME/.dotnet"
export PATH="$DOTNET_ROOT:$DOTNET_ROOT/tools:$PATH"
RCEOF
done

info ".NET $(dotnet --version 2>/dev/null || echo 'installed') ready."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
