#!/usr/bin/env bash
# .NET SDK via Microsoft install script — install
# Generated by tools/generate_scripts.py
set -euo pipefail

# ── helpers ───────────────────────────────────────────────────────────────────
_g="\033[0;32m" _y="\033[0;33m" _r="\033[0;31m" _b="\033[0m"
info()    { echo -e "${_g}[sindri]${_b} $*"; }
warn()    { echo -e "${_y}[warn]${_b}  $*"; }
die()     { echo -e "${_r}[error]${_b} $*" >&2; exit 1; }
has()     { command -v "$1" &>/dev/null; }
require() { has "$1" || die "Required: $1 — install it before running this script."; }

# ── version contract (ADR-024) ─────────────────────────────────────────────────
# SINDRI_COMPONENT_VERSION: injected by the sindri CLI before invoking this script.
# Carries the exact version declared in registry component.yaml.
# Scripts MUST exit 0 without side effects when already at target version.
WANT="${SINDRI_COMPONENT_VERSION:-9.0}"

# Extract semver from binary's version output
version_of() {
    "${1}" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || "${1}" version  2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || echo ""
}

# Return 0 (true) and print status if $1 binary is already at $WANT.
# Return 1 (false) and print upgrade/install intent otherwise.
at_version() {
    local bin="$1" have
    have=$(version_of "$bin")
    if [[ -n "$WANT" && ( "$have" == "$WANT"* || "$have" == *"$WANT"* ) ]]; then
        info "$bin $WANT already installed. Nothing to do."
        return 0
    fi
    [[ -n "$have" ]] && info "$bin: $have → $WANT" || info "Installing $bin $WANT…"
    return 1
}

info "Installing .NET SDK via Microsoft install script…"
require curl

CHANNEL="${DOTNET_CHANNEL:-LTS}"
INSTALL_DIR="${DOTNET_INSTALL_DIR:-$HOME/.dotnet}"
export DOTNET_ROOT="$INSTALL_DIR"
export PATH="$INSTALL_DIR:$PATH"

at_version dotnet && exit 0

info "Fetching dotnet-install.sh (channel: $CHANNEL)…"
curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin \
    --channel "$CHANNEL" \
    --install-dir "$INSTALL_DIR" \
    --no-path \
    || die ".NET install failed."

# Persist to shell rc
for rc in ~/.bashrc ~/.zshrc; do
    [[ -f "$rc" ]] && grep -q "DOTNET_ROOT" "$rc" && continue
    [[ -f "$rc" ]] && cat >> "$rc" <<'RCEOF'

# .NET SDK
export DOTNET_ROOT="$HOME/.dotnet"
export PATH="$DOTNET_ROOT:$DOTNET_ROOT/tools:$PATH"
RCEOF
done

info ".NET $(dotnet --version 2>/dev/null || echo 'installed') ready."
