#!/usr/bin/env bash
# .NET SDK via Microsoft install script — uninstall
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Uninstalling .NET SDK…"
DOTNET_DIR="${DOTNET_ROOT:-$HOME/.dotnet}"
rm -rf "$DOTNET_DIR"
for rc in ~/.bashrc ~/.zshrc; do
    [[ -f "$rc" ]] && sed -i '/DOTNET_ROOT/d' "$rc" 2>/dev/null || true
done
info ".NET SDK removed from $DOTNET_DIR."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
