#!/usr/bin/env bash
# NotebookLM MCP bridge — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Registering NotebookLM MCP bridge with Claude Code…"
require python3
require claude

# Install the MCP bridge via pip/uv
if has uv; then
    uv tool install notebooklm-mcp 2>/dev/null \
        || warn "notebooklm-mcp not on PyPI; may need manual install."
elif has pip3; then
    pip3 install --user notebooklm-mcp 2>/dev/null \
        || warn "notebooklm-mcp not on PyPI; may need manual install."
fi

if claude mcp list 2>/dev/null | grep -q "notebooklm"; then
    warn "NotebookLM MCP bridge already registered. Skipping."
    exit 0
fi

info "Adding NotebookLM MCP bridge…"
claude mcp add notebooklm --scope user -- python3 -m notebooklm_mcp \
    || die "Failed to register NotebookLM MCP bridge."

info "NotebookLM MCP bridge registered. Verify with: claude mcp list"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
