#!/usr/bin/env bash
# NotebookLM MCP bridge — validate
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Validating notebooklm-mcp-cli…"
require notebooklm-mcp-cli
notebooklm-mcp-cli --version >/dev/null 2>&1 || die "notebooklm-mcp-cli not responding."
info "notebooklm-mcp-cli OK"
sindri::emit phase-complete '"change":false'
exit 0

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
