name: Call Sindri Adapter
description: Invokes a Sindri deployment adapter to generate provider-specific configuration

inputs:
  provider:
    description: Provider type (fly, docker, devpod)
    required: true
  sindri-config:
    description: Path to sindri.yaml configuration file (optional - will use fallback if not provided)
    required: false
    default: ""
  output-dir:
    description: Directory to output generated configuration files
    required: false
    default: "."
  app-name:
    description: Override app/workspace name from sindri.yaml
    required: true

outputs:
  config-file:
    description: Path to the generated configuration file
    value: ${{ steps.setup.outputs.config-file }}
  source:
    description: Configuration source (adapter, fallback, or existing)
    value: ${{ steps.setup.outputs.source }}
  vars-json:
    description: Parsed variables as JSON (only when sindri-config provided)
    value: ${{ steps.vars.outputs.json }}

runs:
  using: composite
  steps:
    - name: Validate provider
      shell: bash
      run: |
        VALID_PROVIDERS="fly docker devpod"
        if [[ ! " $VALID_PROVIDERS " =~ " ${{ inputs.provider }} " ]]; then
          echo "::error::Invalid provider: ${{ inputs.provider }}. Must be one of: $VALID_PROVIDERS"
          exit 1
        fi

    - name: Get adapter variables
      id: vars
      if: inputs.sindri-config != ''
      shell: bash
      run: |
        if [[ -f "${{ inputs.sindri-config }}" ]]; then
          ADAPTER="${{ github.workspace }}/deploy/adapters/${{ inputs.provider }}-adapter.sh"
          VARS_JSON=$("$ADAPTER" --output-vars "${{ inputs.sindri-config }}")
          echo "json=$VARS_JSON" >> $GITHUB_OUTPUT
        fi

    - name: Run provider setup
      id: setup
      shell: bash
      run: |
        echo "::group::Running ${{ inputs.provider }} setup"

        HELPER="${{ github.workspace }}/.github/scripts/providers/${{ inputs.provider }}-setup.sh"
        OUTPUT_DIR="${{ inputs.output-dir }}"

        # Build helper arguments based on provider
        case "${{ inputs.provider }}" in
          fly)
            SETUP_ARGS="--app-name ${{ inputs.app-name }} --output-dir $OUTPUT_DIR"
            CONFIG_FILE="$OUTPUT_DIR/fly.toml"
            ;;
          docker)
            SETUP_ARGS="--container-name ${{ inputs.app-name }} --output-dir $OUTPUT_DIR"
            CONFIG_FILE="$OUTPUT_DIR/docker-compose.yml"
            ;;
          devpod)
            SETUP_ARGS="--workspace-name ${{ inputs.app-name }} --output-dir $OUTPUT_DIR"
            CONFIG_FILE="$OUTPUT_DIR/.devcontainer/devcontainer.json"
            ;;
        esac

        # Add sindri-config if provided
        if [[ -n "${{ inputs.sindri-config }}" ]] && [[ -f "${{ inputs.sindri-config }}" ]]; then
          SETUP_ARGS="$SETUP_ARGS --sindri-config ${{ inputs.sindri-config }}"
        fi

        # Run helper script
        # shellcheck disable=SC2086
        OUTPUT=$("$HELPER" $SETUP_ARGS)
        SOURCE=$(echo "$OUTPUT" | grep "^source=" | cut -d= -f2)

        echo "config-file=$CONFIG_FILE" >> $GITHUB_OUTPUT
        echo "source=$SOURCE" >> $GITHUB_OUTPUT

        echo "::endgroup::"

    - name: Display generated config
      shell: bash
      run: |
        echo "::group::Generated configuration (source: ${{ steps.setup.outputs.source }})"
        cat "${{ steps.setup.outputs.config-file }}"
        echo "::endgroup::"
