#!/usr/bin/env bash
# PAL MCP server — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Registering PAL MCP server with Claude Code…"
require claude

if claude mcp list 2>/dev/null | grep -q "pal"; then
    warn "PAL MCP server already registered. Skipping."
    exit 0
fi

info "Adding PAL MCP server…"
claude mcp add pal --scope user -- npx -y @beehiveinnovations/pal-mcp-server \
    || die "Failed to register PAL MCP server."

info "PAL MCP server registered. Verify with: claude mcp list"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
