#!/usr/bin/env bash
# XFCE desktop for Ubuntu containers — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing XFCE desktop environment (Ubuntu/Debian)…"
require apt-get

if dpkg -l xfce4 &>/dev/null 2>&1; then
    warn "XFCE already installed."
else
    info "Installing XFCE4 and essentials…"
    sudo apt-get update -qq
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq \
        xfce4 xfce4-goodies xrdp dbus-x11 x11vnc \
        || die "XFCE install failed."
fi

# Configure xRDP to use XFCE
if has xrdp; then
    echo "startxfce4" | sudo tee /etc/skel/.xsession > /dev/null
    echo "startxfce4" > "$HOME/.xsession"
    sudo systemctl enable xrdp 2>/dev/null || true
    sudo systemctl start  xrdp 2>/dev/null || true
    info "xRDP configured. Connect via Remote Desktop on port 3389."
fi

info "XFCE desktop ready."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
