#!/usr/bin/env bash
# Playwright browsers + system deps — install
# Generated by tools/generate_scripts.py
set -euo pipefail

# ── helpers ───────────────────────────────────────────────────────────────────
_g="\033[0;32m" _y="\033[0;33m" _r="\033[0;31m" _b="\033[0m"
info()    { echo -e "${_g}[sindri]${_b} $*"; }
warn()    { echo -e "${_y}[warn]${_b}  $*"; }
die()     { echo -e "${_r}[error]${_b} $*" >&2; exit 1; }
has()     { command -v "$1" &>/dev/null; }
require() { has "$1" || die "Required: $1 — install it before running this script."; }

# ── version contract (ADR-024) ─────────────────────────────────────────────────
# SINDRI_COMPONENT_VERSION: injected by the sindri CLI before invoking this script.
# Carries the exact version declared in registry component.yaml.
# Scripts MUST exit 0 without side effects when already at target version.
WANT="${SINDRI_COMPONENT_VERSION:-1.48.0}"

# Extract semver from binary's version output
version_of() {
    "${1}" --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || "${1}" version  2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 \
    || echo ""
}

# Return 0 (true) and print status if $1 binary is already at $WANT.
# Return 1 (false) and print upgrade/install intent otherwise.
at_version() {
    local bin="$1" have
    have=$(version_of "$bin")
    if [[ -n "$WANT" && ( "$have" == "$WANT"* || "$have" == *"$WANT"* ) ]]; then
        info "$bin $WANT already installed. Nothing to do."
        return 0
    fi
    [[ -n "$have" ]] && info "$bin: $have → $WANT" || info "Installing $bin $WANT…"
    return 1
}

info "Installing Playwright and browsers…"
require node
require npm

# Playwright version is checked via npx since it may be project-local
_pw_ver=$(npx playwright --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 || echo "")
if [[ -n "$WANT" && "$_pw_ver" == "$WANT"* ]]; then
    info "playwright $WANT already installed. Nothing to do."
    exit 0
fi
[[ -n "$_pw_ver" ]] && info "playwright: $_pw_ver → $WANT" || info "Installing playwright $WANT…"

info "Installing Playwright globally…"
npm install -g playwright \
    || die "npm install -g playwright failed."

info "Installing browser binaries…"
if [[ "${CI:-}" == "true" || "${GITHUB_ACTIONS:-}" == "true" ]]; then
    warn "CI mode: skipping browser downloads."
    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 playwright install 2>/dev/null || true
else
    playwright install || die "playwright install failed."
    playwright install-deps 2>/dev/null || warn "Some system deps may be missing (run with sudo for full install-deps)."
fi

info "Playwright $(playwright --version 2>/dev/null) ready."
