#!/usr/bin/env bash
# Playwright browsers + system deps — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing Playwright and browsers…"
require node
require npm

# Playwright version is checked via npx since it may be project-local
_pw_ver=$(npx playwright --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+(\.[0-9]+)?' | head -1 || echo "")
if [[ -n "$WANT" && "$_pw_ver" == "$WANT"* ]]; then
    info "playwright $WANT already installed. Nothing to do."
    exit 0
fi
[[ -n "$_pw_ver" ]] && info "playwright: $_pw_ver → $WANT" || info "Installing playwright $WANT…"

info "Installing Playwright globally…"
npm install -g playwright \
    || die "npm install -g playwright failed."

info "Installing browser binaries…"
if [[ "${CI:-}" == "true" || "${GITHUB_ACTIONS:-}" == "true" ]]; then
    warn "CI mode: skipping browser downloads."
    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 playwright install 2>/dev/null || true
else
    playwright install || die "playwright install failed."
    playwright install-deps 2>/dev/null || warn "Some system deps may be missing (run with sudo for full install-deps)."
fi

info "Playwright $(playwright --version 2>/dev/null) ready."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
