#!/usr/bin/env bash
# Ollama local LLM runtime — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing Ollama LLM runtime…"
require curl

if [[ "${CI:-}" == "true" || "${GITHUB_ACTIONS:-}" == "true" ]]; then
    warn "CI mode: skipping Ollama (large download). Install manually: curl -fsSL https://ollama.com/install.sh | sh"
    exit 0
fi

at_version ollama && exit 0

case "$(uname -s)" in
    Linux)
        ARCH="$(uname -m)"
        [[ "$ARCH" == "x86_64" ]]  && URL="https://ollama.com/download/ollama-linux-amd64.tar.zst"
        [[ "$ARCH" == "aarch64" ]] && URL="https://ollama.com/download/ollama-linux-arm64.tar.zst"
        [[ -z "${URL:-}" ]] && die "Unsupported arch: $ARCH"
        mkdir -p "$HOME/.local/bin"
        require zstd || { sudo apt-get install -y zstd 2>/dev/null || sudo dnf install -y zstd 2>/dev/null; }
        info "Downloading Ollama (~800 MB)…"
        curl -fsSL "$URL" -o /tmp/ollama.tar.zst
        tar -I zstd -xf /tmp/ollama.tar.zst -C /tmp
        mv /tmp/bin/ollama "$HOME/.local/bin/ollama"
        chmod +x "$HOME/.local/bin/ollama"
        rm -rf /tmp/ollama.tar.zst /tmp/bin
        ;;
    Darwin)
        if has brew; then brew install ollama
        else die "Install Ollama for macOS from https://ollama.com/download"; fi
        ;;
    *) die "Unsupported OS." ;;
esac

has ollama && info "Ollama $(ollama --version 2>/dev/null | head -1) installed." \
          || die "Ollama binary not found after install."
info "Start Ollama with: ollama serve"
info "Pull a model:      ollama pull llama3.2"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
