#!/usr/bin/env bash
# Ollama local LLM runtime — uninstall
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Uninstalling Ollama…"
case "$(uname -s)" in
    Darwin) has brew && brew uninstall ollama 2>/dev/null || true ;;
    Linux)  rm -f "$HOME/.local/bin/ollama" ;;
esac
info "Removing Ollama models (~/.ollama)…"
read -rp "Remove downloaded models (~/.ollama)? [y/N] " ans
[[ "$ans" =~ ^[Yy]$ ]] && rm -rf "$HOME/.ollama" || info "Models retained."
info "Ollama uninstalled."

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
