name: Cleanup DevPod Resources
description: Cleans up DevPod workspaces and provider resources

inputs:
  workspace-id:
    description: Workspace ID to cleanup
    required: false
    default: ""
  cleanup-all:
    description: Cleanup all workspaces
    required: false
    default: "false"
  force:
    description: Force cleanup even if workspace is running
    required: false
    default: "false"
  remove-provider:
    description: Remove the provider after cleanup
    required: false
    default: "false"
  provider-id:
    description: Provider ID to remove
    required: false
    default: ""
  cleanup-volumes:
    description: Also cleanup persistent volumes
    required: false
    default: "true"
  local-cluster-name:
    description: Name of the local cluster to delete (if created during setup)
    required: false
    default: ""
  local-cluster-type:
    description: Type of local cluster (kind or k3d)
    required: false
    default: ""
  local-cluster-created:
    description: Whether a local cluster was created during setup
    required: false
    default: "false"

outputs:
  cleaned-workspaces:
    description: List of cleaned workspace IDs
    value: ${{ steps.cleanup.outputs.cleaned }}
  cleanup-status:
    description: Cleanup operation status
    value: ${{ steps.cleanup.outputs.status }}

runs:
  using: composite
  steps:
    - name: List current workspaces
      shell: bash
      run: |
        echo "::group::Current DevPod workspaces"

        devpod list || echo "No workspaces found"

        echo "::endgroup::"

    - name: Cleanup specific workspace
      if: inputs.workspace-id != ''
      shell: bash
      run: |
        echo "::group::Cleaning up workspace: ${{ inputs.workspace-id }}"

        WORKSPACE_ID="${{ inputs.workspace-id }}"
        FORCE="${{ inputs.force }}"

        # Check if workspace exists
        if devpod list --output json | jq -e ".[] | select(.id == \"$WORKSPACE_ID\")" > /dev/null; then
          # Stop workspace first if not forcing
          if [[ "$FORCE" != "true" ]]; then
            echo "Stopping workspace..."
            devpod stop "$WORKSPACE_ID" || true
            sleep 5
          fi

          # Delete workspace
          echo "Deleting workspace..."
          if [[ "$FORCE" == "true" ]]; then
            devpod delete "$WORKSPACE_ID" --force || true
          else
            devpod delete "$WORKSPACE_ID" || true
          fi

          echo "✅ Workspace $WORKSPACE_ID cleaned up"
        else
          echo "⚠️ Workspace $WORKSPACE_ID not found"
        fi

        echo "::endgroup::"

    - name: Cleanup all workspaces
      if: inputs.cleanup-all == 'true'
      id: cleanup
      shell: bash
      run: |
        echo "::group::Cleaning up all workspaces"

        FORCE="${{ inputs.force }}"
        CLEANED="[]"

        # Get all workspace IDs
        WORKSPACES=$(devpod list --output json | jq -r '.[].id' || echo "")

        if [[ -z "$WORKSPACES" ]]; then
          echo "No workspaces to clean up"
          STATUS="no-workspaces"
        else
          for workspace in $WORKSPACES; do
            echo "Cleaning up workspace: $workspace"

            # Stop workspace
            if [[ "$FORCE" != "true" ]]; then
              devpod stop "$workspace" || true
              sleep 2
            fi

            # Delete workspace
            if [[ "$FORCE" == "true" ]]; then
              devpod delete "$workspace" --force || true
            else
              devpod delete "$workspace" || true
            fi

            # Add to cleaned list
            CLEANED=$(echo "$CLEANED" | jq --arg ws "$workspace" '. + [$ws]')
          done

          STATUS="success"
          echo "✅ All workspaces cleaned up"
        fi

        echo "cleaned=$CLEANED" >> $GITHUB_OUTPUT
        echo "status=$STATUS" >> $GITHUB_OUTPUT

        echo "::endgroup::"

    - name: Cleanup volumes
      if: inputs.cleanup-volumes == 'true'
      shell: bash
      run: |
        echo "::group::Cleaning up volumes"

        # Provider-specific volume cleanup
        PROVIDER_ID="${{ inputs.provider-id }}"

        if [[ -n "$PROVIDER_ID" ]]; then
          # Get provider type
          PROVIDER_TYPE=$(devpod provider list --output json | \
            jq -r ".[] | select(.name == \"$PROVIDER_ID\") | .provider" || echo "")

          case "$PROVIDER_TYPE" in
            docker)
              echo "Cleaning up Docker volumes..."
              docker volume ls --format "{{.Name}}" | grep -E "devpod|sindri" | \
                xargs -r docker volume rm || true
              ;;
            kubernetes)
              echo "Cleaning up Kubernetes PVCs..."
              kubectl get pvc -n devpod --no-headers | grep devpod | \
                awk '{print $1}' | xargs -r kubectl delete pvc -n devpod || true
              ;;
          esac
        fi

        echo "::endgroup::"

    - name: Remove provider
      if: inputs.remove-provider == 'true' && inputs.provider-id != ''
      shell: bash
      run: |
        echo "::group::Removing provider: ${{ inputs.provider-id }}"

        PROVIDER_ID="${{ inputs.provider-id }}"

        # Check if provider exists
        if devpod provider list | grep -q "$PROVIDER_ID"; then
          devpod provider remove "$PROVIDER_ID" || true
          echo "✅ Provider $PROVIDER_ID removed"
        else
          echo "⚠️ Provider $PROVIDER_ID not found"
        fi

        echo "::endgroup::"

    - name: Cleanup local cluster and registry
      if: inputs.local-cluster-created == 'true' && inputs.local-cluster-name != ''
      shell: bash
      run: |
        echo "::group::Cleaning up local cluster and registry"

        CLUSTER_NAME="${{ inputs.local-cluster-name }}"
        CLUSTER_TYPE="${{ inputs.local-cluster-type }}"
        REG_NAME="local-registry-${CLUSTER_NAME}"

        # Delete cluster based on type
        if [[ "$CLUSTER_TYPE" == "kind" ]]; then
          if command -v kind &> /dev/null; then
            if kind get clusters 2>/dev/null | grep -q "^${CLUSTER_NAME}$"; then
              echo "Deleting kind cluster: $CLUSTER_NAME"
              kind delete cluster --name "$CLUSTER_NAME"
              echo "Kind cluster '$CLUSTER_NAME' deleted"
            else
              echo "Kind cluster '$CLUSTER_NAME' not found (already deleted?)"
            fi
          else
            echo "kind CLI not found, skipping cluster cleanup"
          fi
        elif [[ "$CLUSTER_TYPE" == "k3d" ]]; then
          if command -v k3d &> /dev/null; then
            if k3d cluster list 2>/dev/null | grep -q "^${CLUSTER_NAME}"; then
              echo "Deleting k3d cluster: $CLUSTER_NAME"
              k3d cluster delete "$CLUSTER_NAME"
              echo "k3d cluster '$CLUSTER_NAME' deleted"
            else
              echo "k3d cluster '$CLUSTER_NAME' not found (already deleted?)"
            fi
          else
            echo "k3d CLI not found, skipping cluster cleanup"
          fi
        else
          echo "Unknown or empty cluster type: $CLUSTER_TYPE, skipping cluster cleanup"
        fi

        # Delete local registry container
        if [ "$(docker ps -aq -f name="${REG_NAME}" 2>/dev/null)" ]; then
          echo "Stopping and removing local registry: $REG_NAME"
          docker stop "${REG_NAME}" 2>/dev/null || true
          docker rm "${REG_NAME}" 2>/dev/null || true
          echo "Local registry '$REG_NAME' removed"
        else
          echo "Local registry '$REG_NAME' not found (already removed?)"
        fi

        echo "::endgroup::"

    - name: Final status
      shell: bash
      run: |
        echo "::group::Final status"

        echo "Remaining workspaces:"
        devpod list || echo "No workspaces"

        echo "Configured providers:"
        devpod provider list || echo "No providers"

        # Show local clusters if tools are available
        if command -v kind &> /dev/null; then
          echo "Kind clusters:"
          kind get clusters || echo "No kind clusters"
        fi

        if command -v k3d &> /dev/null; then
          echo "k3d clusters:"
          k3d cluster list || echo "No k3d clusters"
        fi

        echo "::endgroup::"
