name: Protected Extensions Tests

on:
  workflow_call:
    inputs:
      test_app_prefix:
        description: 'Test app prefix'
        required: false
        default: 'ext-test'
        type: string
      region:
        description: 'Fly.io region'
        required: false
        default: 'sjc'
        type: string
      skip_cleanup:
        description: 'Skip cleanup for debugging'
        required: false
        default: false
        type: boolean
    secrets:
      FLYIO_AUTH_TOKEN:
        required: true

jobs:
  protected-extensions-tests:
    name: Test Protected Extension Enforcement
    runs-on: ubuntu-latest
    timeout-minutes: 40
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Generate test app name
        id: app-name
        run: |
          timestamp=$(date +%s)
          app_name="${TEST_APP_PREFIX}-protected-${timestamp}"
          echo "app_name=$app_name" >> $GITHUB_OUTPUT

      - name: Create test SSH key
        run: |
          ssh-keygen -t ed25519 -f test_key -N "" -C "protected-test"
          chmod 600 test_key
          chmod 644 test_key.pub

      - name: Prepare fly.toml
        env:
          APP_NAME: ${{ steps.app-name.outputs.app_name }}
          VOLUME_NAME: "test_data"
          VOLUME_SIZE: "10"
          VM_MEMORY: "2048"
          CPU_KIND: "shared"
          CPU_COUNT: "1"
          CI_MODE: "true"
        run: ./scripts/prepare-fly-config.sh --ci-mode

      - name: Deploy test environment
        run: |
          flyctl apps create ${{ steps.app-name.outputs.app_name }} --org personal || true
          flyctl deploy --app ${{ steps.app-name.outputs.app_name }} \
            --strategy immediate \
            --wait-timeout 600 \
            --ha=false

      - name: Wait for deployment
        timeout-minutes: 8
        run: |
          app_name="${{ steps.app-name.outputs.app_name }}"
          max_wait=420
          interval=15
          elapsed=0

          while [ $elapsed -lt $max_wait ]; do
            status_output=$(flyctl status --app $app_name 2>&1 || echo "error")

            if echo "$status_output" | grep -q "running"; then
              echo "✅ Deployment ready"
              break
            elif echo "$status_output" | grep -q "failed\|crashed\|error"; then
              echo "❌ Deployment failed"
              exit 1
            fi

            sleep $interval
            elapsed=$((elapsed + interval))
          done

      - name: Install protected extensions
        run: |
          app_name="${{ steps.app-name.outputs.app_name }}"

          flyctl ssh console --app $app_name --user developer --command "/bin/bash -lc '
            cd /workspace/scripts/lib
            manifest=\"extensions.d/active-extensions.conf\"

            # Add all protected extensions
            echo \"workspace-structure\" > \$manifest
            echo \"mise-config\" >> \$manifest
            echo \"ssh-environment\" >> \$manifest

            bash extension-manager.sh install-all
          '"

      - name: Test cannot deactivate protected extensions
        run: |
          app_name="${{ steps.app-name.outputs.app_name }}"

          echo "Testing that protected extensions cannot be deactivated..."

          flyctl ssh console --app $app_name --user developer --command "/bin/bash -lc '
            cd /workspace/scripts/lib

            for ext in workspace-structure mise-config ssh-environment; do
              echo \"\"
              echo \"Testing deactivation prevention for \$ext...\"

              # Capture exit code before piping to tee
              bash extension-manager.sh deactivate \$ext 2>&1 | tee /tmp/deactivate_\${ext}.log
              deactivate_exit=\${PIPESTATUS[0]}

              if [ \$deactivate_exit -eq 0 ]; then
                echo \"❌ FAIL: \$ext was deactivated (should be protected)\"
                cat /tmp/deactivate_\${ext}.log
                exit 1
              else
                # Check that error message mentions protection
                if grep -qi \"protected\|cannot.*deactivate\" /tmp/deactivate_\${ext}.log; then
                  echo \"✅ PASS: \$ext properly protected from deactivation with correct error message\"
                else
                  echo \"⚠️  \$ext blocked but no protection message found\"
                  cat /tmp/deactivate_\${ext}.log
                fi
              fi
            done

            echo \"\"
            echo \"✅ All protected extensions properly blocked from deactivation\"
          '"

      - name: Test cannot uninstall protected extensions
        run: |
          app_name="${{ steps.app-name.outputs.app_name }}"

          echo "Testing that protected extensions cannot be uninstalled..."

          flyctl ssh console --app $app_name --user developer --command "/bin/bash -lc '
            cd /workspace/scripts/lib

            for ext in workspace-structure mise-config ssh-environment; do
              echo \"\"
              echo \"Testing uninstall prevention for \$ext...\"

              # Capture exit code before piping to tee
              bash extension-manager.sh uninstall \$ext 2>&1 | tee /tmp/uninstall_\${ext}.log
              uninstall_exit=\${PIPESTATUS[0]}

              if [ \$uninstall_exit -eq 0 ]; then
                echo \"❌ FAIL: \$ext was uninstalled (should be protected)\"
                exit 1
              else
                # Check that error message mentions protection
                if grep -qi \"protected\|cannot.*uninstall\" /tmp/uninstall_\${ext}.log; then
                  echo \"✅ PASS: \$ext properly protected from uninstall with correct error message\"
                else
                  echo \"⚠️  \$ext blocked but no protection message found\"
                  cat /tmp/uninstall_\${ext}.log
                fi
              fi
            done

            echo \"\"
            echo \"✅ All protected extensions properly blocked from uninstall\"
          '"

      - name: Test auto-repair manifest (protected extensions missing)
        run: |
          app_name="${{ steps.app-name.outputs.app_name }}"

          echo "Testing auto-repair when protected extensions removed from manifest..."

          flyctl ssh console --app $app_name --user developer --command "/bin/bash -lc '
            cd /workspace/scripts/lib
            manifest=\"extensions.d/active-extensions.conf\"

            echo \"Removing protected extensions from manifest...\"
            # Backup original
            cp \$manifest \${manifest}.backup

            # Remove protected extensions
            sed -i \"/^workspace-structure$/d\" \$manifest
            sed -i \"/^mise-config$/d\" \$manifest
            sed -i \"/^ssh-environment$/d\" \$manifest

            echo \"\"
            echo \"=== Manifest after removal ===\"
            cat \$manifest || echo \"(empty)\"

            echo \"\"
            echo \"Running: extension-manager list (triggers auto-repair)...\"
            bash extension-manager.sh list

            echo \"\"
            echo \"=== Manifest after auto-repair ===\"
            cat \$manifest

            # Verify protected extensions are back
            echo \"\"
            echo \"Verifying protected extensions were restored...\"
            for ext in workspace-structure mise-config ssh-environment; do
              if grep -q \"^\$ext\$\" \$manifest; then
                echo \"✅ \$ext restored to manifest\"
              else
                echo \"❌ \$ext NOT in manifest after auto-repair\"
                exit 1
              fi
            done

            # Verify they are at the top
            echo \"\"
            echo \"Verifying protected extensions are at top of manifest...\"
            head -n 10 \$manifest | grep -E \"^(workspace-structure|mise-config|ssh-environment)$\" || {
              echo \"❌ Protected extensions not at top of manifest\"
              exit 1
            }

            echo \"\"
            echo \"✅ Auto-repair correctly restored protected extensions to top of manifest\"
          '"

      - name: Test protected marker in list output
        run: |
          app_name="${{ steps.app-name.outputs.app_name }}"

          echo "Testing that protected extensions show [PROTECTED] marker..."

          flyctl ssh console --app $app_name --user developer --command "/bin/bash -lc '
            cd /workspace/scripts/lib

            echo \"Running: extension-manager list\"
            output=\$(bash extension-manager.sh list 2>&1)
            echo \"\$output\"

            echo \"\"
            echo \"Checking for [PROTECTED] markers...\"
            for ext in workspace-structure mise-config ssh-environment; do
              if echo \"\$output\" | grep \"\$ext\" | grep -q \"PROTECTED\"; then
                echo \"✅ \$ext shows [PROTECTED] marker\"
              else
                echo \"❌ \$ext missing [PROTECTED] marker\"
                exit 1
              fi
            done

            echo \"\"
            echo \"✅ All protected extensions show [PROTECTED] marker in list output\"
          '"

      - name: Cleanup
        if: always()
        run: |
          app_name="${{ steps.app-name.outputs.app_name }}"

          machines=$(flyctl machine list --app $app_name --json 2>/dev/null | jq -r '.[].id' || echo "")
          for machine in $machines; do
            [[ -z "$machine" ]] && continue
            flyctl machine stop $machine --app $app_name || true
            sleep 2
            flyctl machine destroy $machine --app $app_name --force || true
          done

          volumes=$(flyctl volumes list --app $app_name --json 2>/dev/null | jq -r '.[].id' || echo "")
          for volume in $volumes; do
            [[ -z "$volume" ]] && continue
            flyctl volumes destroy $volume --app $app_name --yes || true
          done

          flyctl apps destroy $app_name --yes || true
          rm -f test_key test_key.pub
