#!/usr/bin/env bash
# Claude Marketplace skill/plugin resolver — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing Claude Marketplace skill resolver…"
require npm
require claude

info "Installing @sindri/marketplace-cli…"
npm install -g @sindri/marketplace-cli 2>/dev/null \
    || npm install -g claudeup 2>/dev/null \
    || warn "Marketplace CLI package not found on npm. Manual install may be required."

info "Claude Marketplace skill resolver installed."
info "Browse skills: https://claude.ai/marketplace"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
