#!/usr/bin/env bash
# PHP language and Composer — install
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Installing PHP and Composer…"

install_via_apt() {
    require apt-get
    sudo apt-get update -qq
    sudo apt-get install -y -qq \
        php php-cli php-common php-curl php-json php-mbstring \
        php-xml php-zip php-intl php-gd 2>/dev/null
}

install_via_dnf() {
    require dnf
    sudo dnf install -y php php-cli php-common php-curl php-json \
        php-mbstring php-xml php-zip php-intl 2>/dev/null
}

install_via_brew() {
    require brew
    brew install php
}

if has php; then
    warn "PHP already installed: $(php --version | head -1). Skipping."
else
    case "$(uname -s)" in
        Linux)
            if has apt-get;  then install_via_apt
            elif has dnf;    then install_via_dnf
            else die "Unsupported Linux package manager. Install PHP manually."
            fi ;;
        Darwin) install_via_brew ;;
        *) die "Unsupported OS." ;;
    esac
    info "PHP $(php --version 2>/dev/null | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+') installed."
fi

# Install Composer
if has composer; then
    warn "Composer already installed: $(composer --version 2>/dev/null | head -1). Skipping."
else
    info "Installing Composer…"
    require curl
    EXPECTED_CHECKSUM="$(curl -sS https://composer.github.io/installer.sig)"
    php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');"
    ACTUAL_CHECKSUM="$(php -r "echo hash_file('sha384', '/tmp/composer-setup.php');")"
    [[ "$EXPECTED_CHECKSUM" == "$ACTUAL_CHECKSUM" ]] || die "Composer installer checksum mismatch."
    php /tmp/composer-setup.php --quiet --install-dir="$HOME/.local/bin" --filename=composer
    rm /tmp/composer-setup.php
    info "Composer $(composer --version 2>/dev/null | head -1) installed."
fi

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
