#!/usr/bin/env bash
# PHP language and Composer — validate
# Generated by tools/generate_scripts.py (ADR-030 contract).
# Do not edit directly; modify the body in tools/generate_scripts.py
# and re-run `python3 tools/generate_scripts.py`.
set -Eeuo pipefail

. "$SINDRI_HELPERS_SH"
sindri::init

# `WANT` aliases the target version env var so existing per-component
# bodies that reference `$WANT` keep reading naturally.
WANT="$SINDRI_COMPONENT_VERSION"

info "Validating PHP and Composer…"
require php
php --version | head -1 || die "php --version failed."
require composer
composer --version | head -1 || die "composer --version failed."
info "PHP OK: $(php --version | head -1)"
info "Composer OK: $(composer --version | head -1)"

# ADR-030: signal a successful run that did real work. The skip path
# (`sindri::at_version … && exit 0`) emits `change:false` and exits
# before reaching here.
sindri::emit phase-complete '"change":true'
